"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, BookOpen, CalendarDays, CircleHelp, ShieldCheck, Sparkles } from "lucide-react";
import { useProfile } from "@/components/seeded-profile";
import { DisclaimerLine } from "@/components/shared";
import { useLang } from "@/lib/lang";
import { buildJournalRecap, buildPremiumReport, nameMappingLabel, parseLifeContextForReport } from "@/lib/premium-report";
import { KEYS } from "@/lib/storage";

function subscribeContext(onChange: () => void) {
  const handleStorage = (event: StorageEvent) => {
    if (!event.key || event.key === KEYS.lifeContext) onChange();
  };
  window.addEventListener("storage", handleStorage);
  window.addEventListener("focus", onChange);
  return () => {
    window.removeEventListener("storage", handleStorage);
    window.removeEventListener("focus", onChange);
  };
}

function contextSnapshot(): string | null {
  try { return window.localStorage.getItem(KEYS.lifeContext); } catch { return null; }
}

function subscribeJournal(onChange: () => void) {
  const handleStorage = (event: StorageEvent) => { if (!event.key || event.key === KEYS.journal || event.key === KEYS.lifeContext) onChange(); };
  window.addEventListener("storage", handleStorage);
  window.addEventListener("focus", onChange);
  return () => { window.removeEventListener("storage", handleStorage); window.removeEventListener("focus", onChange); };
}

function journalSnapshot(birthDate: string): string | null {
  try {
    const context = parseLifeContextForReport(window.localStorage.getItem(KEYS.lifeContext), birthDate);
    if (!context?.journalAnalysisConsent) return null;
    return window.localStorage.getItem(KEYS.journal);
  } catch { return null; }
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="mb-5 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h2 className="mt-2 font-display text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h2>{description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p> : null}</div>;
}

const KIND_LABELS = {
  en: { calculated: "Calculated", customer: "Your input", tradition: "Tradition lens", scenario: "Planning scenario", insufficient: "Context needed" },
  hi: { calculated: "Ganit se nikla", customer: "Aapka input", tradition: "Parampara ka lens", scenario: "Planning drishya", insufficient: "Sanket ke liye sandarbh chahiye" },
};

export default function PremiumReport() {
  const { profile, reading, today } = useProfile();
  const { lang } = useLang();
  const hi = lang === "hi";
  const nameTableLabel = profile ? nameMappingLabel(profile.system) : "Pythagorean-style";
  const rawContext = React.useSyncExternalStore(subscribeContext, contextSnapshot, () => null);
  const context = profile ? parseLifeContextForReport(rawContext, profile.birthDate) : null;
  const profileBirthDate = profile?.birthDate ?? "";
  const consentedJournalSnapshot = React.useCallback(() => profileBirthDate ? journalSnapshot(profileBirthDate) : null, [profileBirthDate]);
  const rawJournal = React.useSyncExternalStore(subscribeJournal, consentedJournalSnapshot, () => null);
  if (!profile || !reading) return <div className="py-16 text-center"><p className="text-sm text-muted-foreground">{hi ? "Pehle apna profile poora karein." : "Complete your profile first."}</p><Link href="/" className="mt-3 inline-block text-sm text-primary underline">{hi ? "Shuru karein" : "Start"}</Link></div>;

  const report = buildPremiumReport({ profile, reading, context, year: today.getFullYear(), month: today.getMonth() + 1, lang: hi ? "hi" : "en" });
  const localToday = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
  const journalRecap = buildJournalRecap(rawJournal, context?.journalAnalysisConsent === true, localToday, profile.birthDate);
  const dateParts = profile.birthDate.split("-");
  const dateLabel = `${dateParts[2]}/${dateParts[1]}/${dateParts[0]}`;
  const nav = [
    ["summary", hi ? "Mukhya tasveer" : "The reading"],
    ["chart", hi ? "Ank aur ganit" : "Numbers & method"],
    ["journal-recap", hi ? "Journal recap" : "Journal recap"],
    ["timeline", hi ? "Aapka ateet" : "Your timeline"],
    ["scenarios", hi ? "Aage ke drishya" : "Forward scenarios"],
    ["months", hi ? "12-mahine ka naksha" : "12-month map"],
    ["method", hi ? "Seema aur tareeqa" : "Scope & method"],
  ];

  return <main className="premium-report print-full mx-auto max-w-5xl pb-16">
    <div className="no-print mb-8 flex flex-wrap items-center justify-between gap-3">
      <Link href="/overview" className="text-sm text-primary underline underline-offset-4">← {hi ? "Overview par lautein" : "Back to overview"}</Link>
      <Link href="/calibration" className="inline-flex h-10 items-center gap-2 rounded-lg border px-3 text-sm hover:bg-accent"><BookOpen aria-hidden className="size-4" />{hi ? "Input jodein / sudhaarein" : "Add or correct context"}</Link>
    </div>

    <header className="relative overflow-hidden rounded-[2rem] border bg-card/90 p-6 shadow-xl shadow-primary/5 sm:p-10">
      <div aria-hidden className="pointer-events-none absolute -right-16 -top-20 size-64 rounded-full border border-primary/10" />
      <div aria-hidden className="pointer-events-none absolute -right-5 -top-9 size-44 rounded-full border border-primary/10" />
      {profile.isDemoProfile ? <aside role="note" className="relative mb-5 rounded-xl border border-amber-500/50 bg-amber-500/10 px-4 py-3 text-sm leading-6">
        <strong>{hi ? "Namoona data · personal report nahi" : "Sample data · not a personal report"}</strong>
        <span className="ml-1">{hi ? "Yeh Aarav Mehta ka kalpanik demo profile hai. Apni reading ke liye apne janm-vivaran bharein." : "This is the fictional Aarav Mehta demo profile. Enter your own birth details to see your reading."}</span>
      </aside> : null}
      <div className="relative max-w-3xl">
        <p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-primary"><Sparkles aria-hidden className="size-4" />{hi ? "Anko Ki Maya · vyaktigat report" : "Anko Ki Maya · personal report"}</p>
        <h1 className="mt-4 font-display text-4xl font-semibold leading-tight tracking-tight sm:text-6xl">{hi ? "Aapki zindagi. Aapke ank. Saaf hisaab." : "Your life. Your numbers. A clear-eyed reading."}</h1>
        <p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{profile.preferredName || profile.birthName} <span aria-hidden>·</span> {dateLabel} <span aria-hidden>·</span> {hi ? `naam-table: ${nameTableLabel}` : `name mapping: ${nameTableLabel}`} <span aria-hidden>·</span> {hi ? `taiyaar ${today.toLocaleDateString("en-IN")}` : `prepared ${today.toLocaleDateString("en-IN")}`}</p>
        <p className="mt-5 max-w-2xl border-l-2 border-primary/40 pl-4 text-sm leading-6">{hi ? "Yeh koi crystal-ball verdict nahi. Ganit ko alag, paramparagat arth ko alag, aur aapke apne tajurbe ko sabse aage rakha gaya hai." : "This is not a crystal-ball verdict. The calculations, traditional interpretations, and your own lived experience are kept distinct."}</p>
      </div>
      <div className="relative mt-8 flex flex-wrap gap-2">{report.evidence.map((item) => <span key={item.kind} className="rounded-full border bg-background/70 px-3 py-1.5 text-xs"><span className="font-semibold">{KIND_LABELS[hi ? "hi" : "en"][item.kind]}</span><span className="hidden sm:inline"> · {item.label}</span></span>)}</div>
    </header>

    <aside role="note" className="mt-4 rounded-xl border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm leading-6">
      <strong>{hi ? "Automated working draft · Human review abhi baaki" : "Automated working draft · Human review required"}</strong>
      <span className="ml-1">{hi ? "Yeh app output final ya reviewer-approved report nahi hai. Customer ko dene se pehle authorized human reviewer ki jaanch aur sign-off zaroori hai." : "This app output is not a final or reviewer-approved report. An authorized human reviewer must check and sign off before customer delivery."}</span>
    </aside>

    <nav aria-label={hi ? "Report ke bhaag" : "Report sections"} className="no-print sticky top-0 z-20 my-5 flex gap-2 overflow-x-auto rounded-xl border bg-background/95 p-2 backdrop-blur">{nav.map(([id, label]) => <a key={id} href={`#${id}`} className="shrink-0 rounded-lg px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-accent hover:text-foreground">{label}</a>)}</nav>

    <section id="summary" className="scroll-mt-20 py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "01 · Mukhya tasveer" : "01 · Executive reading"} title={hi ? "Kya aapke baare mein kehna theek hai — aur kya nahi" : "What we can say about you—and what we cannot"} description={hi ? "Har vyaktigat baat ka apna source hai. Jahan source kam hai, report saaf kehti hai." : "Every personal statement has a source. Where the source is thin, the report says so plainly."} />
      <div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]">
        <article className="rounded-2xl border bg-card p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{hi ? "Aapke data se nikla saar" : "Grounded synthesis"}</p><p className="mt-3 text-base leading-8 sm:text-lg">{report.summary}</p></article>
        <aside className="rounded-2xl bg-primary p-5 text-primary-foreground sm:p-7"><p className="text-xs font-semibold uppercase tracking-wider opacity-75">{hi ? "Ek asli sawaal" : "The question worth sitting with"}</p><h3 className="mt-3 font-display text-xl font-semibold leading-7">{report.keyQuestion}</h3><p className="mt-5 text-sm leading-6 opacity-80">{hi ? "Iska jawaab ank nahi denge. Aapke agle chhote kadam aur dekhe ja sakne waale nateeje denge." : "The numbers cannot answer this. Your next small step and its observable result can."}</p></aside>
      </div>
      {report.patternQuestion ? <article className="mt-4 rounded-2xl border border-gold/30 bg-secondary/35 p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{hi ? "Aapke bataye sandarbh se nikla, jaanchne layak sawaal" : "A testable question from your stated context"}</p><p className="mt-2 text-sm leading-6">{report.patternQuestion}</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{hi ? "Yeh aapke jawab se bani parikalpana hai—janmank se personality diagnosis nahi." : "This is a hypothesis prompted by your answers—not a personality diagnosis from birth numbers."}</p></article> : null}
      {report.userFacts.length ? <div className="mt-5 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 sm:p-7"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck aria-hidden className="size-4 text-primary" />{hi ? "Aapke diye hue tathya — app ke guess nahi" : "Your own account—not an app guess"}</h3><ul className="mt-3 space-y-3">{report.userFacts.map((fact, index) => <li key={`${index}-${fact}`} className="border-l border-primary/30 pl-3 text-sm leading-6">{fact}</li>)}</ul><p className="mt-4 text-xs text-muted-foreground">{hi ? "In notes ko settings/calibration mein sudhaar ya delete kar sakte hain." : "You can edit or delete these notes in Calibration or Settings."}</p></div> : <div className="mt-5 flex gap-3 rounded-2xl border border-dashed p-5"><CircleHelp aria-hidden className="mt-0.5 size-5 shrink-0 text-primary" /><div><h3 className="font-semibold">{hi ? "Aapki kahani ke bina, hum kahani nahi ghadte." : "Without your story, we will not invent one."}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{hi ? "Aapke chune hue saal, faisle aur vartamaan sthiti jodne se report aur aapke beech sachcha sambandh dikhega—janm-tithi se chhupe hue waaqiye nahi." : "Add selected years, decisions, and current circumstances to make the report truly about you—not to make it pretend your birth date reveals hidden events."}</p><Link href="/calibration" className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary underline">{hi ? "Apna sandarbh jodein" : "Add your context"}<ArrowUpRight aria-hidden className="size-4" /></Link></div></div>}
    </section>

    <section id="chart" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "02 · Ganit aur vyakhya" : "02 · Calculations & interpretation"} title={hi ? "Har number ka hisaab saamne" : "Every number, with its working"} description={hi ? "Yeh aapke selected numerology system ka hisaab hai. Parampara arth deti hai; woh nateeje ka pramaan nahi." : "These calculations follow the numerology system you selected. Tradition offers meaning; it does not establish outcomes."} />
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{report.calculations.map((item) => <article key={item.label} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{item.label}</p><p className="mt-2 font-display text-5xl text-primary">{item.value}</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-primary">{hi ? "ganit" : "calculated"}</span></div><details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-xs font-semibold">{hi ? "Hisaab kholein" : "Show calculation"}</summary><ol className="mt-3 list-decimal space-y-1 pl-4 text-xs leading-5 text-muted-foreground">{item.steps.map((step, index) => <li key={`${index}-${step}`}>{step}</li>)}</ol></details></article>)}</div>
      <div className="mt-5 grid gap-4 md:grid-cols-2">
        <article className="rounded-2xl border p-5"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-full bg-primary text-xl text-primary-foreground">{report.cycle}</span><h3 className="font-semibold">{hi ? `Personal Year ${report.cycle} · paramparagat lens` : `Personal Year ${report.cycle} · traditional lens`}</h3></div><p className="mt-3 text-sm leading-6">{report.cycleLens[0].toUpperCase() + report.cycleLens.slice(1)}.</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{report.cycleMethod}</p></article>
        <article className="rounded-2xl border p-5"><h3 className="font-semibold">{hi ? "Chart mein dohraav aur farq" : "Repetition and contrast in your chart"}</h3><p className="mt-2 text-sm leading-6">{report.convergence.repeated.length ? (hi ? `Core positions mein ${report.convergence.repeated.join(", ")} dobara aate hain. Ise ek ganitiya dohraav samjhein—kai swatantra saboot nahi.` : `The number${report.convergence.repeated.length > 1 ? "s" : ""} ${report.convergence.repeated.join(", ")} recur${report.convergence.repeated.length === 1 ? "s" : ""} across core positions. This is a mathematical repetition, not multiple independent pieces of evidence.`) : (hi ? "Core numbers alag-alag aaye hain. Inke alag roles hain; sirf farq ko virodh ya samasya nahi kehte." : "The core numbers differ. They occupy different roles; difference alone is not a contradiction or a problem.")}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{report.convergence.preservedMasters.length ? (hi ? `Master number ${report.convergence.preservedMasters.map((item) => `${item.number} (${item.positions.join(", ")})`).join("; ")} ke roop mein bacha hai. Yeh isi system ka calculation rule hai.` : `Preserved master number${report.convergence.preservedMasters.length > 1 ? "s" : ""}: ${report.convergence.preservedMasters.map((item) => `${item.number} (${item.positions.join(", ")})`).join("; ")}. This is a calculation convention within the selected system.`) : (hi ? "Is reading ke core results mein 11, 22 ya 33 master number ke roop mein nahi bacha." : "No 11, 22, or 33 is preserved as a master number in these core results.")}</p></article>
      </div>
      <section className="mt-6 rounded-2xl border bg-card/70 p-5 sm:p-7" aria-labelledby="life-chapters-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">{hi ? "Paramparagat life-cycle ganit" : "Traditional life-cycle calculations"}</p><h3 id="life-chapters-heading" className="mt-1 font-display text-xl font-semibold">{hi ? "Pinnacles aur Challenges" : "Pinnacles & Challenges"}</h3></div><p className="max-w-md text-xs leading-5 text-muted-foreground">{hi ? "Yeh age windows aur number formulas hain—jeevan ki ghatnaon ka calendar ya pakka outcome nahi." : "These are age windows and number formulas—not a calendar of life events or a guaranteed outcome."}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{report.pinnacles.map((item) => <article key={item.index} className="rounded-xl border p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{hi ? `Pinnacle ${item.index}` : `Pinnacle ${item.index}`}</p><p className="mt-1 font-display text-4xl text-primary">{item.number}</p><p className="mt-1 text-xs">{hi ? `umar ${item.ageStart}–${item.ageEnd === Infinity ? "aage" : item.ageEnd}` : `ages ${item.ageStart}–${item.ageEnd === Infinity ? "onward" : item.ageEnd}`}</p></article>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{report.challenges.map((item) => <article key={item.index} className="rounded-xl border p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{hi ? `${item.label} Challenge` : `${item.label} Challenge`}</p><p className="mt-1 font-display text-3xl">{item.number}</p></article>)}</div><details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-xs font-semibold">{hi ? "Pinnacles ka formula" : "Pinnacle formula"}</summary><ol className="mt-2 list-decimal space-y-1 pl-4 text-xs leading-5 text-muted-foreground">{report.pinnacleSteps.map((step) => <li key={step}>{step}</li>)}</ol></details><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold">{hi ? "Challenges ka formula" : "Challenge formula"}</summary><ol className="mt-2 list-decimal space-y-1 pl-4 text-xs leading-5 text-muted-foreground">{report.challengeSteps.map((step) => <li key={step}>{step}</li>)}</ol></details></section>
    </section>

    <section id="journal-recap" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "03 · Aapki journal, aapki awaaz" : "03 · Your journal, in your words"} title={hi ? "Pichhle 7 aur 30 din — sirf aapke likhe hue notes" : "Your last 7 and 30 days—only what you wrote"} description={hi ? "Yeh recap tabhi aata hai jab aap Calibration mein journal-use ki alag sahmati dein. Isse ank se ateet jaanne ka daava nahi hota." : "This recap appears only when you separately opt in under Calibration. It does not claim that numbers reveal your past."} />
      {!context?.journalAnalysisConsent ? <div className="rounded-2xl border border-dashed p-5"><p className="text-sm leading-6 text-muted-foreground">{hi ? "Journal recap shamil nahi hai. Aapki sahmati ke bina app journal entries ko is report mein padhta ya dikhata nahi." : "Journal recap is not included. Without your consent, this report does not read or show journal entries."}</p><Link href="/calibration" className="mt-2 inline-flex text-sm font-semibold text-primary underline">{hi ? "Calibration mein optional sahmati dekhein" : "Review the optional consent in Calibration"}</Link></div> : <>
        <p className="mb-4 rounded-xl bg-muted/40 p-4 text-xs leading-5 text-muted-foreground">{hi ? "Yeh entries isi browser mein saved aapke journal se hain; yahan koi upload nahi hota. Entries ka count journal activity batata hai, zindagi mein kya hua uska swatantra satyapan nahi. Print/PDF mein sensitive notes aa sakte hain." : "These entries come from the journal saved in this browser; nothing is uploaded here. Counts describe journal activity, not independent verification of life events. Printing/exporting may include sensitive notes."}</p>
        <div className="grid gap-4 lg:grid-cols-2">
          {([["7", journalRecap?.week ?? []], ["30", journalRecap?.month ?? []]] as const).map(([days, entries]) => <article key={days} className="rounded-2xl border bg-card p-5"><h3 className="font-display text-xl font-semibold">{hi ? `Pichhle ${days} din` : `Past ${days} days`} <span className="font-sans text-xs font-normal text-muted-foreground">· {entries.length} {hi ? "entries" : "entries"}</span></h3>{entries.length ? <ul className="mt-3 space-y-3">{entries.map((entry, index) => <li key={`${entry.date}-${index}`} className="rounded-xl bg-muted/35 p-3"><p className="text-[11px] font-semibold text-primary">{entry.date} · {entry.category} · {entry.mood}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">“{entry.text}”</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{hi ? "Is daayre mein koi valid journal entry nahi mili." : "No valid journal entries were found in this window."}</p>}</article>)}
        </div><Link href="/calibration" className="mt-3 inline-flex text-xs font-medium text-primary underline">{hi ? "Journal recap ki sahmati badlein" : "Change journal recap consent"}</Link>
      </>}
    </section>

    <section id="timeline" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "04 · Aapki timeline" : "04 · Your timeline"} title={hi ? "Ateet ke baare mein sirf utna, jitna aapne bataya" : "The past, only as far as you have told us"} description={hi ? "Janmank kisi breakup, naukri, nuksaan, beemari ya parivaarik waaqiye ka saboot nahi. Yeh tareekhein aur notes aapke apne hain." : "A birth number is not evidence of a breakup, job change, loss, illness, or family event. These dates and notes are yours."} />
      {report.timeline.length ? <><p className="mb-4 rounded-xl bg-secondary/35 p-4 text-sm leading-6">{report.timelinePattern}</p><div className="relative ml-3 border-l border-primary/25 pl-6">{report.timeline.map((item) => <article key={`${item.year}-${item.note}`} className="relative mb-4 rounded-xl border bg-card p-4 sm:p-5"><span aria-hidden className="absolute -left-[1.93rem] top-5 size-3 rounded-full border-2 border-primary bg-background" /><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-display text-2xl">{item.year} <span className="font-sans text-xs text-muted-foreground">· {item.area}</span></h3><span className="rounded-full border px-2.5 py-1 text-[10px] text-muted-foreground">{hi ? `Personal Year ${item.cycle} · ganit` : `Personal Year ${item.cycle} · calculated`}</span></div><p className="mt-3 text-sm leading-6">“{item.note}”</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{hi ? "Aapka note is saal ke cycle ke saath rakha hai; yeh cycle ghatna ka kaaran ya bhavishyavaani nahi." : "Your note is placed beside that year's cycle. The cycle is not a cause or prediction of the event."}</p></article>)}</div></> : <div className="rounded-2xl border border-dashed p-6 text-sm leading-6 text-muted-foreground"><p>{hi ? "Abhi koi ateet ka turning point share nahi hua. Report use khud se nahi bharegi." : "No past turning points have been shared yet. This report will not fill them in for you."}</p><Link href="/calibration" className="mt-2 inline-flex font-semibold text-primary underline">{hi ? "Timeline jodein" : "Add timeline anchors"}</Link></div>}
    </section>

    <section id="scenarios" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "05 · Aage ke drishya" : "05 · Forward scenarios"} title={hi ? "Bhavishyavaani nahi—teen raaste, jaanchne ke sanket" : "Not predictions—three paths and signals to test"} description={hi ? "Yeh sambhavnayein aapke focus aur aapke diye sandarbh par planning exercise hain. Koi bhi waaqiya hone ka daava nahi." : "These are planning exercises based on your focus and the context you shared. None claims an event will occur."} />
      {report.scenarios.length ? <div className="grid gap-3 lg:grid-cols-3">{report.scenarios.map((scenario, index) => <article key={scenario.title} className="flex flex-col rounded-2xl border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{hi ? `Raasta ${index + 1}` : `Path ${index + 1}`}</p><h3 className="mt-2 font-display text-xl font-semibold">{scenario.title}</h3><p className="mt-2 inline-flex self-start rounded-full bg-secondary/55 px-2.5 py-1 text-[10px] font-semibold">{scenario.horizon}</p><p className="mt-3 text-sm font-medium leading-6">{scenario.condition}</p><div className="mt-4 space-y-3 text-xs leading-5"><p><span className="font-semibold text-emerald-700">{hi ? "Mumkin faayda" : "Possible upside"} · </span>{scenario.upside}</p><p><span className="font-semibold text-amber-700">{hi ? "Mumkin keemat" : "Possible cost"} · </span>{scenario.downside}</p><p><span className="font-semibold">{hi ? "Kya dekhna hai" : "Signal to watch"} · </span>{scenario.signal}</p><p><span className="font-semibold">{hi ? "Kaunsi baat ise galat dikhayegi" : "What would count against it"} · </span>{scenario.counterSignal}</p></div><div className="mt-auto border-t pt-4"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-primary"><ArrowDown aria-hidden className="size-3" />{hi ? "Palatne-yogya agla kadam" : "Reversible next step"}</p><p className="mt-2 text-xs leading-5">{scenario.nextStep}</p><aside className="mt-3 rounded-lg bg-secondary/35 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{hi ? "Is raaste ka aadhar" : "Why this scenario is here"}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{scenario.basis}</p></aside></div></article>)}</div> : <div className="rounded-2xl border border-dashed p-6"><p className="font-semibold">{hi ? "Aage ka personal drishya abhi nahi." : "No personal forward scenario yet."}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{hi ? "Pehle apna vartamaan focus aur challenge bataayein. Tab bhi report ghatna nahi, sirf shart-aadhaarit raaste degi." : "Share your present focus and challenge first. Even then, the report will offer conditional paths, not event claims."}</p><Link href="/calibration" className="mt-3 inline-flex text-sm font-semibold text-primary underline">{hi ? "Sthiti bataayein" : "Describe your situation"}</Link></div>}
    </section>

    <section id="months" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "06 · Aane wale 12 mahine" : "06 · The next 12 months"} title={hi ? "Mahine-dar-mahine cycle naksha — guarantee nahi" : "A month-by-month map—not a promise"} description={hi ? "Har Personal Month ke saath paramparagat lens, sochne ka ek sawaal aur chhota practical kadam diya hai. Yeh calendar kisi ghatna ya nateeje ki bhavishyavaani nahi karta." : "Each Personal Month pairs a traditional lens with a question and a small practical step. This calendar does not predict an event or outcome."} />
      {report.monthAnchor ? <p className="mb-4 rounded-xl border border-primary/15 bg-primary/[.035] p-4 text-sm leading-6">{report.monthAnchor}</p> : <p className="mb-4 rounded-xl border border-dashed p-4 text-sm leading-6 text-muted-foreground">{hi ? "Yeh general cycle-reflection hai. Apna faisla, lakshya ya vartamaan sthiti Calibration mein jodenge toh sawaal us sandarbh se jud paayenge." : "This is a general cycle reflection. Add a decision, goal, or current situation in Calibration to connect the prompts to your own context."} <Link href="/calibration" className="ml-1 font-semibold text-primary underline">{hi ? "Sandarbh jodein" : "Add context"}</Link></p>}
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {report.months.map((month) => <article key={`${month.year}-${month.month}`} className="flex flex-col rounded-2xl border bg-card p-5">
          <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">{month.label}</p><h3 className="mt-1 font-display text-2xl font-semibold">{hi ? "Personal Month" : "Personal Month"} {month.personalMonth}</h3></div><span className="shrink-0 rounded-full bg-secondary/55 px-2.5 py-1 text-[10px]">{hi ? `Personal Year ${month.personalYear}` : `Personal Year ${month.personalYear}`}</span></div>
          <p className="mt-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{hi ? "Paramparagat lens" : "Traditional lens"}</p><p className="mt-1 text-sm leading-6">{month.lens}.</p>
          <p className="mt-3 text-xs font-semibold uppercase tracking-wider text-primary">{hi ? "Jaanchne ka sawaal" : "Question to test"}</p><p className="mt-1 text-sm leading-6">{month.question}</p>
          <p className="mt-3 text-xs font-semibold uppercase tracking-wider">{hi ? "Chhota kadam" : "Small move"}</p><p className="mt-1 text-sm leading-6">{month.move}</p>
          <p className="mt-3 border-t pt-3 text-xs leading-5 text-muted-foreground"><span className="font-semibold">{hi ? "Dhyaan rahe" : "Watch for"} · </span>{month.watchOut}</p>
        </article>)}
      </div>
      <details className="mt-4 rounded-xl border px-4 py-3">
        <summary className="cursor-pointer text-sm font-semibold">{hi ? "Sabhi 12 mahino ka ganit aur niyam dekhein" : "Show the working and rule for all 12 months"}</summary>
        <div className="mt-3 space-y-3 text-xs leading-5 text-muted-foreground"><p>{hi ? "App ka calendar-year convention: Personal Year (1 Jan–31 Dec) + calendar month, phir reduction se Personal Month. 11/22/33 bachein toh number dikhaya jaata hai; practical prompt mein uska reduced digit (11→2, 22→4, 33→6) liya jaata hai. Ganit paramparagat hai; sawaal, kadam aur watch-out app ka apna planning framework hai—yeh kisi classical book ka fixed rule ya outcome ka saboot nahi." : "App calendar-year convention: Personal Year (Jan 1–Dec 31) + calendar month, then reduce to Personal Month. If 11/22/33 remain, the number is displayed as-is; its reduced digit (11→2, 22→4, 33→6) supplies the practical prompt. The arithmetic is traditional; the questions, actions, and watch-outs are this app's planning framework—not fixed rules from a classical book or evidence of an outcome."}</p><ol className="grid gap-x-6 gap-y-1 sm:grid-cols-2">{report.months.map((month) => <li key={`${month.year}-${month.month}`}>{month.label}: Personal Year {month.personalYear} + calendar month {month.month} → Personal Month {month.personalMonth} ({month.calculation})</li>)}</ol></div>
      </details>
    </section>

    <section className="border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "07 · Agle 30 din" : "07 · Your next 30 days"} title={hi ? "Ek kadam. Ek sanket. Phir dobara dekhein." : "One step. One signal. Then review."} description={hi ? "Mehnge ya palatna mushkil faisle se pehle ek chhota prayog chunein." : "Before an expensive or hard-to-reverse decision, choose a small experiment."} />
      <div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border p-5"><CalendarDays aria-hidden className="size-5 text-primary" /><h3 className="mt-3 font-semibold">{hi ? "1 · Kadam likhein" : "1 · Define the action"}</h3><p className="mt-2 text-sm leading-6">{report.scenarios[0]?.nextStep ?? report.keyQuestion}</p></article><article className="rounded-2xl border p-5"><ArrowUpRight aria-hidden className="size-5 text-primary" /><h3 className="mt-3 font-semibold">{hi ? "2 · Saboot chunein" : "2 · Choose the evidence"}</h3><p className="mt-2 text-sm leading-6">{hi ? "Kaunsa naapne-yogya badlaav bataayega ki aap apne lakshya ki taraf badhe? Ek tareekh aur ek maap likhein." : "What observable change would show progress toward your goal? Write down one measure and a review date."}</p></article><article className="rounded-2xl border p-5"><CircleHelp aria-hidden className="size-5 text-primary" /><h3 className="mt-3 font-semibold">{hi ? "3 · Na-milne par badlein" : "3 · Revise when it misses"}</h3><p className="mt-2 text-sm leading-6">{hi ? "Agar sanket na dikhe, toh ank ko sahi saabit karne ki koshish na karein. Apni yojana ko badlein." : "If the signal does not appear, do not bend the reading to make it seem right. Update your plan."}</p></article></div>
      {report.remedy ? <article className="mt-5 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">{hi ? "Vyavaharik upaay · bina khareed, bina guarantee" : "Practical remedy · no purchase, no promise"}</p><h3 className="mt-2 font-display text-xl font-semibold">{hi ? "Jis cheez par aapka niyantran hai, wahin se shuru karein" : "Start with what is within your control"}</h3><p className="mt-3 text-sm leading-6">{report.remedy.practice}</p><p className="mt-3 border-t pt-3 text-xs leading-5 text-muted-foreground"><strong>{hi ? "Is cycle ka saavdhaani-sawaal:" : "A caution to carry with this cycle:"}</strong> {report.remedy.caution}</p><p className="mt-3 text-[11px] leading-5 text-muted-foreground">{hi ? "Yeh aadat/faisla par aadharit reflection hai—upchaar nahi, aur koi parinaam pakka nahi." : "This is a behavior-level reflection—not treatment, and not a promised outcome."}</p></article> : null}
    </section>

    <section id="method" className="scroll-mt-20 border-t py-8 sm:py-12">
      <SectionHeading eyebrow={hi ? "08 · Tareeqa aur imaandari" : "08 · Method & limits"} title={hi ? "Is report ki seema saaf hai" : "The limits are part of the reading"} />
      <div className="grid gap-3 md:grid-cols-2"><article className="rounded-2xl border bg-card p-5"><h3 className="font-semibold">{hi ? "Hum kya karte hain" : "What this report does"}</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>{hi ? `Naam-aadhaarit ankon ke liye ${nameTableLabel} letter-table use hoti hai. Yeh naam selected table convention batata hai, prediction ka saboot nahi. Janm-tithi ke ank alag dikhaye gaye formulas se nikalte hain; naam-table unhe nahi badalti.` : `Uses the ${nameTableLabel} letter table for name-based numbers. This label identifies the selected table convention; it is not evidence of predictive accuracy. Date-based numbers follow their displayed formulas and do not change with the name table.`}</li><li>{hi ? "Aaj ki name+birthdate numerology ko Pythagoras ki pracheen practice kehne ka hum daava nahi karte. Personal Year ko sirf paramparagat reflection lens ke roop mein rakhte hain." : "We do not claim modern name-and-birthdate numerology was an ancient Pythagorean practice. Personal Year is shown only as a traditional reflection lens."}</li><li>{hi ? "Aapke notes ko aapke notes ke roop mein quote karke correction ka adhikaar deti hai." : "Quotes your notes as your notes and leaves room for correction."}</li></ul><p className="mt-4 border-t pt-3 text-xs leading-5 text-muted-foreground">{hi ? "Itihaas ka source (predictive accuracy ka saboot nahi): " : "Historical reference (not evidence of predictive accuracy): "}<a href="https://discovery.ucl.ac.uk/id/eprint/1529408/" target="_blank" rel="noopener noreferrer" className="underline">Andrew Gregory, “The Pythagoreans: Number and Numerology” (2015)</a>.</p></article><article className="rounded-2xl border bg-card p-5"><h3 className="font-semibold">{hi ? "Hum kya daava nahi karte" : "What this report does not claim"}</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>{hi ? "Aapke ank ateet ki chhupi ghatna ya kisi vyakti ke iraade jaante hain." : "Your numbers reveal hidden past events or another person's intentions."}</li><li>{hi ? "Naukri, shaadi, sehat, paisa ya kisi nuksaan ka nateeja pakka hai." : "A job, marriage, health, money, or loss outcome is certain."}</li><li>{hi ? "Ratna, pooja ya khareedi hui remedy se nuksaan rukega." : "A gemstone, ritual, or paid remedy will prevent harm."}</li></ul></article></div>
      <div className="mt-4 rounded-xl bg-muted/40 p-4 text-xs leading-5 text-muted-foreground"><p><strong>{hi ? "Privacy:" : "Privacy:"}</strong> {hi ? "Is app ke is build mein profile aur context isi browser ke local storage mein hain; yahan se report server par upload nahi hoti. Shared device par ise private data samjhein." : "In this build, profile and context stay in this browser's local storage; this report is not uploaded to a server. Treat it as private data on a shared device."}</p><p className="mt-2"><strong>{hi ? "Commercial scope:" : "Commercial scope:"}</strong> {hi ? "Is screen par payment ya paid delivery ka flow configured nahi. Numerology paramparagat vishwas/paddhati hai, pakki bhavishyavaani ka vaigyanik roop se pramaanit tareeqa nahi." : "This screen has no payment or paid-delivery flow configured. Numerology is a traditional belief/practice, not a scientifically established method of certain prediction."}</p></div>
      <div className="mt-6 flex flex-wrap gap-3"><Link href="/calibration" className="inline-flex h-11 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground">{hi ? "Apna sandarbh sudhaarein" : "Correct your context"}</Link><Link href="/settings" className="inline-flex h-11 items-center rounded-lg border px-4 text-sm font-semibold">{hi ? "Data export / delete" : "Export / delete data"}</Link></div>
    </section>
    <footer className="border-t pt-6"><DisclaimerLine /><p className="mt-3 text-center text-[10px] text-muted-foreground">{hi ? `Naam-aadhaarit ankon mein ${nameTableLabel} letter-table aur tareekh ${today.toLocaleDateString("en-IN")} ke formulas. Ganit dobara jaancha ja sakta hai; vyakhya par aapki rai prathamik hai.` : `Name-based numbers use the ${nameTableLabel} letter-mapping convention; date-based formulas are listed above. Prepared ${today.toLocaleDateString("en-IN")}. Calculations are reproducible; your own judgment takes priority over interpretation.`}</p></footer>
  </main>;
}
