"""Canonical Devanagari→Hinglish word dictionary (v3.2 copy pass)."""

DICT = {
 "और": "aur",
 "का": "ka",
 "की": "ki",
 "के": "ke",
 "को": "ko",
 "में": "mein",
 "से": "se",
 "पर": "par",
 "इस": "is",
 "इसी": "isi",
 "है": "hai",
 "हैं": "hain",
 "है।": "hai.",
 "हैं।": "hain.",
 "हो": "ho",
 "होगा": "hoga",
 "होगा।": "hoga.",
 "था": "tha",
 "था।": "tha.",
 "थी": "thi",
 "हुआ": "hua",
 "हुई": "hui",
 "हुए": "hue",
 "एक": "ek",
 "यह": "yeh",
 "यही": "yehi",
 "यहाँ": "yahan",
 "वह": "woh",
 "वही": "wahi",
 "वहीं": "wahin",
 "वहाँ": "wahan",
 "वो": "woh",
 "जो": "jo",
 "जो।": "jo.",
 "क्योंकि": "kyunki",
 "लेकिन": "lekin",
 "जब": "jab",
 "तब": "tab",
 "जहाँ": "jahan",
 "वो।": "woh.",
 "कोई": "koi",
 "कुछ": "kuchh",
 "नहीं": "nahi",
 "नहीं।": "nahi.",
 "न": "na",
 "ही": "hi",
 "भी": "bhi",
 "भी।": "bhi.",
 "तो": "toh",
 "या": "ya",
 "और।": "aur.",
 "से।": "se.",
 "कर": "kar",
 "करता": "karta",
 "करते": "karte",
 "करती": "karti",
 "करना।": "karna.",
 "करने": "karne",
 "करें": "karein",
 "करें।": "karein.",
 "कीजिए": "kijiye",
 "कीजिए।": "kijiye.",
 "रखें": "rakhein",
 "रखें।": "rakhein.",
 "रखिए": "rakhiye",
 "रखिए।": "rakhiye.",
 "रखता": "rakhta",
 "दें।": "dein.",
 "देता": "deta",
 "देगा।": "dega.",
 "देखें": "dekhein",
 "दो": "do",
 "लें": "lein",
 "लेती": "leti",
 "लेकर": "lekar",
 "देकर": "dekar",
 "बना": "bana",
 "बनाता": "banata",
 "बनाएँ": "banao",
 "जाता": "jaata",
 "जाती": "jaati",
 "जाए": "jaaye",
 "आते": "aate",
 "आने": "aane",
 "आएगा": "aayega",
 "होते": "hote",
 "होती": "hoti",
 "होता": "hota",
 "रहा": "raha",
 "रही": "rahi",
 "गया": "gaya",
 "पहले": "pehle",
 "बाद": "baad",
 "आगे": "aage",
 "पीछे": "peechhe",
 "नीचे": "neeche",
 "ऊपर": "upar",
 "अब": "ab",
 "अभी": "abhi",
 "अगले": "agle",
 "अगला": "agla",
 "अगली": "agli",
 "पिछले": "pichhle",
 "इसलिए": "isliye",
 "फिर": "phir",
 "जैसा": "jaisa",
 "जैसे": "jaise",
 "जिस": "jis",
 "उस": "us",
 "उन्हीं": "unhi",
 "सबसे": "sabse",
 "हर": "har",
 "साथ": "saath",
 "संग": "sang",
 "लिए": "liye",
 "बिना": "bina",
 "तक": "tak",
 "बहुत": "bahut",
 "ज़्यादा": "zyada",
 "कम": "kam",
 "ज़रूरी": "zaroori",
 "आप": "aap",
 "आपका": "aapka",
 "आपकी": "aapki",
 "आपके": "aapke",
 "आपको": "aapko",
 "आपसे": "aapse",
 "आपने": "aapne",
 "अपना": "apna",
 "अपनी": "apni",
 "अपने": "apne",
 "मैं": "main",
 "मेरा": "mera",
 "हम": "hum",
 "दोनों": "dono",
 "तीनों": "teeno",
 "दोनों।": "dono.",
 "सभी": "sabhi",
 "सब": "sab",
 "लोग": "log",
 "लोगों": "logon",
 "बात": "baat",
 "बातें": "baatein",
 "काम": "kaam",
 "कार्य": "kaarya",
 "दिन": "din",
 "रात": "raat",
 "साल": "saal",
 "साल।": "saal.",
 "सालों": "saalon",
 "वर्ष": "saal",
 "वर्षों": "saalon",
 "महीना": "mahina",
 "महीने": "mahine",
 "महीनों": "mahinon",
 "हफ़्ते": "hafte",
 "हफ्ते": "hafte",
 "रोज़": "roz",
 "रोज़ाना": "rozana",
 "समय": "samay",
 "वक्त": "waqt",
 "उम्र": "umra",
 "आयु": "aayu",
 "दशक": "dashak",
 "दशकों": "dashakon",
 "जन्म": "janm",
 "जीवन": "jeevan",
 "जीवन।": "jeevan.",
 "परिवार": "parivaar",
 "पारिवारिक": "parivaarik",
 "घर": "ghar",
 "गृह": "grih",
 "माँ": "Maa",
 "पिता": "pita",
 "बच्चे": "bachche",
 "बच्चों": "bachchon",
 "बड़ों": "badon",
 "बुज़ुर्गों": "buzurgon",
 "दोस्ती": "dosti",
 "मित्र": "mitra",
 "साझेदारी": "saajhedari",
 "रिश्ता": "rishta",
 "रिश्ते": "rishte",
 "प्रेम": "prem",
 "प्यार": "pyaar",
 "शादी": "shaadi",
 "शादी-प्यार": "shaadi-pyaar",
 "विवाह": "vivaah",
 "धन": "dhan",
 "पैसा": "paisa",
 "पैसों": "paison",
 "कमाई": "kamai",
 "बचत": "bachat",
 "बकाया": "baqaya",
 "रोकड़ा": "roqda",
 "लाभ": "laabh",
 "हानि": "haani",
 "ऋण": "ran",
 "कर्ज़": "karz",
 "ब्याज": "byaaj",
 "बिल": "bill",
 "खर्च": "kharch",
 "संपत्ति": "sampatti",
 "जायदाद": "jaayadad",
 "विरासत": "virasat",
 "करियर": "career",
 "नौकरी": "naukri",
 "नौकरी/एडमिशन": "naukri/admission",
 "व्यापार": "vyaapaar",
 "बिज़नेस": "business",
 "उद्यम": "udyam",
 "लॉन्च": "launch",
 "प्रस्ताव": "prastaav",
 "सौदा": "sauda",
 "सौदों": "saudon",
 "संपर्क": "sampark",
 "नेटवर्क": "network",
 "दफ़्तर": "daftar",
 "ग्राहक": "graahak",
 "ग्राहकों": "graahakon",
 "ग्राहकों।": "graahakon.",
 "पदोन्नति": "padonnati",
 "सफलता": "safalta",
 "असफलता": "asafalta",
 "जीत": "jeet",
 "हार": "haar",
 "जीतेंगे": "jeetenge",
 "शुरुआत": "shuruaat",
 "शुरू": "shuru",
 "आरंभ": "aarambh",
 "समापन": "samaapan",
 "अंत": "ant",
 "पूरा": "poora",
 "पूरी": "poori",
 "पूरा।": "poora.",
 "अधूरा": "adhura",
 "अधूरा।": "adhura.",
 "यात्रा": "yatra",
 "यात्राएँ": "yatraayein",
 "विदेश": "videsh",
 "विदेशी": "videshi",
 "स्थानांतरण": "sthaanaantaran",
 "गमन": "gaman",
 "देश": "desh",
 "शहर": "shehar",
 "जगह": "jagah",
 "नाम": "naam",
 "शोहरत": "shohrat",
 "दृश्यता": "drishyata",
 "प्रसिद्धि": "prasiddhi",
 "मंच": "manch",
 "स्टेज": "stage",
 "अध्याय": "adhyay",
 "पाठ": "paath",
 "पढ़ा": "padha",
 "पढ़ी": "padhi",
 "अध्ययन": "adhyayan",
 "विद्या": "vidya",
 "ज्ञान": "gyaan",
 "बुद्धि": "buddhi",
 "दिमाग़": "dimaag",
 "मन": "man",
 "मन।": "man.",
 "मनोबल": "manobal",
 "सोच": "soch",
 "विचार": "vichaar",
 "संवाद": "samvaad",
 "वाणी": "vaani",
 "बोली": "boli",
 "भाषा": "bhasha",
 "शब्द": "shabd",
 "शब्दों": "shabdon",
 "शक्ति": "shakti",
 "बल": "bal",
 "ऊर्जा": "oorja",
 "तेज़": "tez",
 "धीमा": "dheema",
 "तीव्रता": "teevrata",
 "अति": "ati",
 "अत्यंत": "atyant",
 "गहरा": "gehra",
 "गहराई": "gehrai",
 "गहरी": "gehri",
 "छोटा": "chhota",
 "छोटे": "chhote",
 "छोटी": "chhoti",
 "बड़ा": "bada",
 "बड़े": "bade",
 "बड़ी": "badi",
 "बड़ों।": "badon.",
 "डबल": "double",
 "ट्रिपल": "triple",
 "दोगुना": "doguna",
 "दोगुनी": "doguni",
 "दोगुना।": "doguna.",
 "तीन": "teen",
 "चार": "chaar",
 "पाँच": "paanch",
 "छह": "chheh",
 "सात": "saat",
 "आठ": "aath",
 "नौ": "nau",
 "दस": "das",
 "शून्य": "shoonya",
 "अंक": "ank",
 "अंकों": "ankon",
 "अंक।": "ank.",
 "मूलांक": "Mulank",
 "भाग्यांक": "Bhagyank",
 "नामांक": "Namank",
 "अंक-दशा": "Ank Dasha",
 "दशा": "dasha",
 "दशा।": "dasha.",
 "अंक-चक्र": "Ank-chakra",
 "ग्रह": "graha",
 "ग्रहों": "grahon",
 "ग्रह।": "graha.",
 "योग": "yog",
 "योग।": "yog.",
 "राजयोग": "Rajyoga",
 "राजयोग।": "Rajyoga.",
 "राजयोगों": "Rajyogon",
 "चक्र": "chakra",
 "कुंडली": "kundali",
 "कुंडली।": "kundali.",
 "राशि": "rashi",
 "नक्षत्र": "nakshatra",
 "तिथि": "tithi",
 "युति": "yuti",
 "युतियाँ": "yutiyaan",
 "दृष्टि": "drishti",
 "भाव": "bhav",
 "भावों": "bhavon",
 "लग्न": "lagna",
 "चंद्र": "Chandra",
 "चंद्रमा": "Chandrama",
 "सूर्य": "Surya",
 "आदित्य": "Aditya",
 "गुरु": "Guru",
 "बृहस्पति": "Brihaspati",
 "बुध": "Budh",
 "शुक्र": "Shukra",
 "शनि": "Shani",
 "मंगल": "Mangal",
 "राहु": "Rahu",
 "केतु": "Ketu",
 "सूर्याय": "Suryaya",
 "चंद्राय": "Chandraya",
 "गुरवे": "Gurave",
 "बुधाय": "Budhaya",
 "शुक्राय": "Shukraya",
 "शनैश्चराय": "Shanicharaya",
 "राहवे": "Rahave",
 "केतवे": "Ketave",
 "भौमाय": "Bhaumaya",
 "नमः": "namah",
 "सः": "sah",
 "श्रां": "Shraam",
 "श्रीं": "Shreem",
 "श्रौं": "Shraum",
 "ह्रां": "Hraam",
 "ह्रीं": "Hreem",
 "ह्रौं": "Hraum",
 "ग्रां": "Graam",
 "ग्रीं": "Greem",
 "ग्रौं": "Graum",
 "भ्रां": "Bhraam",
 "भ्रीं": "Bhreem",
 "भ्रौं": "Bhraum",
 "बां": "Baam",
 "बीं": "Beem",
 "बौं": "Baum",
 "द्रां": "Draam",
 "द्रीं": "Dreem",
 "द्रौं": "Draum",
 "स्रां": "Sraam",
 "स्रीं": "Sreem",
 "स्रौं": "Sraum",
 "प्रां": "Praam",
 "प्रीं": "Preem",
 "प्रौं": "Praum",
 "क्रां": "Kraam",
 "क्रीं": "Kreem",
 "क्रौं": "Kraum",
 "ॐ": "ॐ",
 "मंत्र": "mantra",
 "यंत्र": "yantra",
 "यंत्र।": "yantra.",
 "जप": "japa",
 "जप।": "japa.",
 "दान": "daan",
 "व्रत": "vrat",
 "पूजा": "pooja",
 "अभिषेक": "abhishek",
 "मंदिर": "mandir",
 "दर्शन": "darshan",
 "आरती": "aarti",
 "प्रसाद": "prasaad",
 "स्वामी": "Swami",
 "हनुमान": "Hanuman",
 "गणेश": "Ganesh",
 "लक्ष्मी": "Lakshmi",
 "दुर्गा": "Durga",
 "शिव": "Shiv",
 "शिवलिंग": "shivling",
 "रुद्राक्ष": "rudraksh",
 "रुद्राक्ष।": "rudraksh.",
 "बाँह": "baanh",
 "बाँह।": "baanh.",
 "सोमवार": "Somvaar",
 "मंगलवार": "Mangalvaar",
 "बुधवार": "Budhvaar",
 "गुरुवार": "Guruvaar",
 "शुक्रवार": "Shukravaar",
 "शनिवार": "Shanivaar",
 "रविवार": "Ravivaar",
 "प्रातः": "praatah",
 "प्रातःकाल": "praatahkaal",
 "सूर्योदय": "sooryoday",
 "सूर्योदय।": "sooryoday.",
 "सूर्यास्त": "sooryaast",
 "मध्याह्न": "madhyahna",
 "रंग": "rang",
 "रंगों": "rangon",
 "रत्न": "ratna",
 "रत्नों": "ratnon",
 "रत्न।": "ratna.",
 "माणिक्य": "Maanikya",
 "मोती": "Moti",
 "मोती।": "Moti.",
 "पुखराज": "Pukhraj",
 "गोमेद": "Gomed",
 "पन्ना": "Panna",
 "हीरा": "Heera",
 "नीलम": "Neelam",
 "मूँगा": "Moonga",
 "मूँग": "moong",
 "लहसुनिया": "Lehsunia",
 "चाँदी": "chaandi",
 "सोना": "sona",
 "तांबा": "taamba",
 "लोहा": "loha",
 "सीसा": "seesa",
 "मसूर": "masoor",
 "चने": "chane",
 "हल्दी": "haldi",
 "चावल": "chaawal",
 "दूध": "doodh",
 "दही": "dahi",
 "मिश्री": "mishri",
 "कपूर": "kapoor",
 "गुड़": "gud",
 "तिल": "til",
 "नारियल": "naariyal",
 "काले": "kaale",
 "काला": "kaala",
 "नीला": "neela",
 "नीली": "neeli",
 "हरा": "hara",
 "हरी": "hari",
 "हरे": "hare",
 "पीला": "peela",
 "पीली": "peeli",
 "पीले": "peele",
 "सफ़ेद": "safed",
 "श्वेत": "shwet",
 "सफ़ेद।": "safed.",
 "लाल": "laal",
 "धूसर": "dhoosar",
 "गुलाबी": "gulaabi",
 "क्रीम": "cream",
 "वस्त्र": "vastra",
 "वस्त्रों": "vastaron",
 "वस्तु": "vastu",
 "वस्तुएँ": "vastuyein",
 "पुष्प": "pushp",
 "पुष्पों": "pushpon",
 "फल": "phal",
 "फलों": "phalon",
 "पत्ते": "patte",
 "पत्तियाँ": "pattiyaan",
 "पत्ता": "patta",
 "जल": "jal",
 "जल।": "jal.",
 "दूर": "door",
 "कपड़े": "kapde",
 "कंबल": "kambal",
 "कंबल।": "kambal.",
 "सेवा": "seva",
 "सेवा।": "seva.",
 "दान।": "daan.",
 "दान-वस्तु": "daan-vastu",
 "दान-वस्तु।": "daan-vastu.",
 "अनुशासन": "anushasan",
 "संयम": "sanyam",
 "धैर्य": "dhairya",
 "सब्र": "sabr",
 "परीक्षा": "pariksha",
 "जाँच": "jaanch",
 "जाँचवाएँ": "jaanchwaayein",
 "सलाह": "salah",
 "संकल्प": "sankalp",
 "निर्णय": "nirnay",
 "निर्णयों": "nirnayon",
 "फैसला": "faisla",
 "संकेत": "sanket",
 "संकेतों": "sanketon",
 "स्थिर": "sthir",
 "स्थिरता": "sthirta",
 "स्थायी": "sthaayi",
 "चंचल": "chanchal",
 "शांत": "shaant",
 "शांत।": "shaant.",
 "संतुलन": "santulan",
 "संतुलन।": "santulan.",
 "तनाव": "tanaav",
 "बेचैनी": "bechaini",
 "बेचैनी।": "bechaini.",
 "चिंता": "chinta",
 "चिंतन": "chintan",
 "ध्यान": "dhyaan",
 "एकाग्रता": "ekaagrata",
 "स्वप्न": "sapne",
 "नींद": "neend",
 "सुबह": "subah",
 "शाम": "shaam",
 "रुटीन": "routine",
 "आदत": "aadat",
 "आदतें": "aadatein",
 "आदतें।": "aadatein.",
 "मेहनत": "mehnat",
 "परिश्रम": "parishram",
 "जुनून": "junoon",
 "पैशन": "passion",
 "इच्छा": "ichchha",
 "आत्म": "aatm",
 "आत्म-इच्छा": "aatm-ichchha",
 "आत्मविश्वास": "aatmvishvaas",
 "अहंकार": "ahankaar",
 "अहं": "aham",
 "गर्व": "garv",
 "साहस": "saahas",
 "डर": "dar",
 "डर।": "dar.",
 "भय": "bhay",
 "क्रोध": "krodh",
 "क्रोध-संयम": "krodh-sanyam",
 "क्रोध।": "krodh.",
 "गुस्सा": "gussa",
 "शोर": "shor",
 "शोर।": "shor.",
 "शोरगोल": "shorgol",
 "प्रबल": "prabal",
 "प्रबल।": "prabal.",
 "मज़बूत": "mazboot",
 "कमज़ोर": "kamzor",
 "कमज़ोरी": "kamzori",
 "अच्छा": "achchha",
 "अच्छे": "achchhe",
 "बुरा": "bura",
 "बुरे": "bure",
 "भारी": "bhaari",
 "भारी।": "bhaari.",
 "सफ़ल": "safal",
 "सुरक्षित": "surakshit",
 "खतरा": "khatra",
 "ख़तरा": "khatra",
 "जोखिम": "jokhim",
 "सावधानी": "saavdhani",
 "सावधानी।": "saavdhani.",
 "सावधान": "saavdhaan",
 "धोखा": "dhokha",
 "गलत": "galat",
 "सही": "sahi",
 "सच": "sach",
 "सच।": "sach.",
 "सच्चा": "sachcha",
 "सच्चाई": "sachchai",
 "पूर्ण": "poora",
 "अपूर्ण": "apurn",
 "अध्यायों": "adhyayon",
 "खिड़की": "khidki",
 "खिड़कियाँ": "khidkiyaan",
 "खिड़कियाँ।": "khidkiyaan.",
 "खिड़कियों": "khidkiyon",
 "खिड़की।": "khidki.",
 "रेखा": "rekha",
 "रेखाएँ": "rekhaayein",
 "रेखा।": "rekha.",
 "चढ़ाव": "chadhaav",
 "उतार": "utaar",
 "उतार-चढ़ाव": "utaar-chadhaav",
 "लहर": "lahar",
 "लहरें": "lahrein",
 "लहरों": "lahron",
 "लय": "lay",
 "ताल": "taal",
 "ताल-मेल": "taal-mel",
 "ग्राफ़": "graph",
 "ग्राफ़।": "graph.",
 "समय-रेखा": "samay-rekha",
 "समय-रेखा।": "samay-rekha.",
 "मोड़": "mod",
 "मोड़।": "mod.",
 "मोड़-बिंदु": "mod-bindu",
 "शिखर": "shikhar",
 "चोटी": "choti",
 "नींव": "neev",
 "नींव।": "neev.",
 "आधार": "aadhaar",
 "स्तंभ": "stambh",
 "दीवार": "deewar",
 "दीवारों": "deewaron",
 "दरवाज़ा": "darwaaza",
 "दरवाज़े": "darwaaze",
 "छत": "chhat",
 "कमरा": "kamra",
 "कमरे": "kamre",
 "कमरे।": "kamre.",
 "भीड़": "bheed",
 "भीड़।": "bheed.",
 "भीड़ों": "bheedon",
 "राजा": "raja",
 "राजा।": "raja.",
 "राजा-महाराजा": "raja-maharaja",
 "योद्धा": "yoddha",
 "सिपाही": "sipaahi",
 "न्यायाधीश": "nyaayaadheesh",
 "जज": "judge",
 "शिक्षक": "shikshak",
 "गुरुजन": "gurujan",
 "पंडित": "pandit",
 "तपस्वी": "tapasvi",
 "साधु": "saadhu",
 "साधु।": "saadhu.",
 "महात्मा": "mahatma",
 "सेठ": "seth",
 "बाज़ार": "baazaar",
 "बाज़ार।": "baazaar.",
 "बाज़ारों": "baazaaron",
 "मंडी": "mandi",
 "दुकान": "dukaan",
 "खेत": "khet",
 "खिलौने": "khilone",
 "खेल": "khel",
 "जश्न": "jashn",
 "जश्न।": "jashn.",
 "त्योहार": "tyohaar",
 "त्योहारों": "tyohaaron",
 "मौसम": "mausam",
 "मौसम।": "mausam.",
 "मौसमों": "mausamon",
 "ऋतु": "ritu",
 "ऋतुओं": "rituon",
 "वर्षा": "varsha",
 "गर्मी": "garmi",
 "सर्दी": "sardi",
 "बसंत": "basant",
 "गति": "gati",
 "गति।": "gati.",
 "रफ़्तार": "raftaar",
 "रफ़्तार।": "raftaar.",
 "स्पीडोमीटर": "speedometer",
 "दौर": "daur",
 "दौर।": "daur.",
 "दौरों": "dauron",
 "काल": "kaal",
 "काल।": "kaal.",
 "काले।": "kaale.",
 "काल-चक्र": "kaal-chakra",
 "चक्र।": "chakra.",
 "मोड़ों": "modon",
 "अंदर": "andar",
 "बाहर": "bahar",
 "आस-पास": "aas-paas",
 "इधर-उधर": "idhar-udhar",
 "आर-पार": "aar-paar",
 "चारों": "charon",
 "तरफ़": "taraf",
 "तरफ़।": "taraf.",
 "दिशा": "disha",
 "दिशाएँ": "dishaayein",
 "बिंदु": "bindu",
 "बिंदुओं": "binduon",
 "रेखा-बिंदु": "rekha-bindu",
 "केंद्र": "kendra",
 "मूल": "mool",
 "मूल।": "mool.",
 "जड़": "jad",
 "जड़ों": "jadon",
 "शाखा": "shaakha",
 "सूत्र": "sootra",
 "तंत्र": "tantra",
 "युग": "yug",
 "युगों": "yugon",
 "कल्प": "kalp",
 "सृजन": "srijan",
 "सृजन।": "srijan.",
 "रचना": "rachna",
 "रचना।": "rachna.",
 "कला": "kala",
 "कला।": "kala.",
 "कलाकार": "kalakaar",
 "कारीगरी": "kaarigari",
 "कारीगर": "kaarigar",
 "डिज़ाइन": "design",
 "डिज़ाइनर": "designer",
 "सौंदर्य": "saundarya",
 "विलास": "vilaas",
 "आराम": "aaraam",
 "सुख": "sukh",
 "दुख": "dukh",
 "सुख।": "sukh.",
 "प्रसन्नता": "prasannata",
 "खुशी": "khushi",
 "खुशी।": "khushi.",
 "हँसी": "hansi",
 "आनंद": "anand",
 "उमंग": "umang",
 "उत्साह": "utsaah",
 "जोश": "josh",
 "जोश।": "josh.",
 "होंसला": "honsla",
 "हिम्मत": "himmat",
 "इज़्ज़त": "izzat",
 "सम्मान": "samman",
 "प्रतिष्ठा": "pratishtha",
 "प्रतिष्ठा।": "pratishtha.",
 "कीर्ति": "keerti",
 "अभिव्यक्ति": "abhivyakti",
 "अभिव्यक्ति।": "abhivyakti.",
 "विश्वास": "vishvaas",
 "भरोसा": "bharosa",
 "भरोसा।": "bharosa.",
 "ज़िम्मेदारी": "zimmewari",
 "ज़िम्मेदारी।": "zimmewari.",
 "फ़र्ज़": "farz",
 "फर्ज़": "farz",
 "कर्तव्य": "kartavya",
 "देखभाल": "dekhbhaal",
 "देखभाल।": "dekhbhaal.",
 "परवा": "parwa",
 "परवाह": "parwah",
 "केयर": "care",
 "केयर।": "care.",
 "संरक्षण": "sanrakshan",
 "पालन": "paalan",
 "पालन।": "paalan.",
 "अनुग्रह": "anugrah",
 "आशीर्वाद": "aashirwaad",
 "कृपा": "kripa",
 "वरदान": "vardaan",
 "वरदान।": "vardaan.",
 "परंपरा": "parampara",
 "परंपरा।": "parampara.",
 "परंपरा का": "parampara ka",
 "परंपरागत": "paramparagat",
 "परंपरा।।": "parampara.",
 "शास्त्र": "shastra",
 "शास्त्रों": "shastron",
 "शास्त्रीय": "shaastriya",
 "वेद": "Ved",
 "वेदों": "Vedon",
 "उपनिषद्": "Upanishad",
 "ज्योतिष": "jyotish",
 "ज्योतिष।": "jyotish.",
 "ज्योतिषी": "jyotishi",
 "ज्योतिषी।": "jyotishi.",
 "गणित": "ganit",
 "गणित।": "ganit.",
 "कारण-गणित": "kaaran-ganit",
 "हिसाब": "hisaab",
 "हिसाब।": "hisaab.",
 "हिसाब-किताब": "hisaab-kitaab",
 "बही": "bahee",
 "लेखा": "lekha",
 "खाता": "khaata",
 "खाता।": "khaata.",
 "लगाम": "lagaam",
 "बुझकर": "boojhkar",
 "बूझकर": "boojhkar",
 "जानबूझकर": "jaan-boojhkar",
 "जान": "jaan",
 "जान।": "jaan.",
 "बूझ": "boojh",
 "चाल": "chaal",
 "चाल।": "chaal.",
 "चालाकी": "chaalaki",
 "चतुराई": "chaturaai",
 "चतुर": "chatur",
 "तर्क": "tark",
 "तर्क।": "tark.",
 "तर्कशील": "tarkasheel",
 "विश्लेषण": "vishleshan",
 "विश्लेषण।": "vishleshan.",
 "सोच-विचार": "soch-vichaar",
 "दृष्टिकोण": "drishtikon",
 "नज़र": "nazar",
 "नज़रों": "nazron",
 "देखना": "dekhna",
 "दिखना": "dikhna",
 "दिखना।": "dikhna.",
 "दिखाओ": "dikhao",
 "दिखाएँ": "dikhao",
 "दिखाना": "dikhana",
 "प्रकट": "prakat",
 "प्रकट।": "prakat.",
 "प्रकाशित": "prakashit",
 "प्रकाशित।": "prakashit.",
 "प्रकाश": "prakaash",
 "रोशनी": "roshni",
 "रोशनी।": "roshni.",
 "रोशन": "roshan",
 "अंधेरा": "andhera",
 "अंधेरा।": "andhera.",
 "छाया": "chhaya",
 "छाया।": "chhaya.",
 "परछाईं": "parchhai",
 "उजाला": "ujala",
 "दीया": "diya",
 "दीया।": "diya.",
 "दीपक": "deepak",
 "लौ": "lau",
 "लौ।": "lau.",
 "ज्योति": "jyoti",
 "ज्योति।": "jyoti.",
 "अग्नि": "agni",
 "अग्नि।": "agni.",
 "इंजन": "engine",
 "मशीन": "machine",
 "मशीनें": "machinen",
 "मशीनों": "machinon",
 "फायर": "fire",
 "जलाती": "jalaati",
 "जलाता": "jalaata",
 "बुझ": "bujh",
 "बुझना": "bujhna",
 "बुझा": "bujha",
 "बुझाता": "bujhaata",
 "रोकना": "rokna",
 "रोकें": "rokein",
 "रोका": "roka",
 "टूट": "toot",
 "टूट।": "toot.",
 "टूटना": "tootna",
 "टूटे": "toote",
 "तोड़": "tod",
 "तोड़ो": "todo",
 "तोड़ता": "todta",
 "जोड़": "jod",
 "जोड़।": "jod.",
 "जोड़ो": "jodo",
 "जोड़ता": "jodta",
 "जोड़ी": "jodi",
 "जोड़ी।": "jodi.",
 "जjodi": "jodi",
 "मरम्मत": "marammat",
 "मरम्मत।": "marammat.",
 "निर्माण": "nirmaan",
 "निर्माण।": "nirmaan.",
 "गठन": "gathan",
 "व्यवस्था": "vyavastha",
 "व्यवस्था।": "vyavastha.",
 "प्रबंध": "prabandh",
 "इंतज़ाम": "intezam",
 "प्रबंधों": "prabandhon",
 "योजना": "yojana",
 "योजना।": "yojana.",
 "योजनाएँ": "yojanaayein",
 "योजनाओं": "yojanaon",
 "प्रोजेक्ट": "project",
 "प्रोजेक्टों": "projecton",
 "मिशन": "mission",
 "मिशन।": "mission.",
 "लक्ष्य": "lakshya",
 "लक्ष्य।": "lakshya.",
 "मक़सद": "maqsad",
 "मक़सद।": "maqsad.",
 "उद्देश्य": "uddeshya",
 "सपना": "sapna",
 "सपनों": "sapnon",
 "सपने": "sapne",
 "सपने।": "sapne.",
 "ख्वाब": "khwab",
 "अभी-अभी": "abhi-abhi",
 "अभी-अभी।": "abhi-abhi.",
 "भविष्य": "bhavishya",
 "भविष्य।": "bhavishya.",
 "भूत।": "past.",
 "भविष्य।।": "bhavishya.",
 "वर्तमान": "vartmaan",
 "वर्तमान।": "vartmaan.",
 "प्रस्तुत": "prastut",
 "प्रस्तुत।": "prastut.",
 "स्कूल": "school",
 "कॉलेज": "college",
 "पढ़ाई": "padhai",
 "दाखिला": "daakhila",
 "एडमिशन": "admission",
 "नतीजा": "nateeja",
 "नतीजों": "nateejon",
 "परीक्षा।": "pariksha.",
 "परिणाम": "parinaam",
 "परिणाम।": "parinaam.",
 "फलाफल": "phalaaphal",
 "खाद्य": "khaadya",
 "स्वास्थ्य": "swasthya",
 "स्वास्थ्य।": "swasthya.",
 "सेहत": "sehat",
 "शरीर": "shareer",
 "शरीर।": "shareer.",
 "मौसम-विज्ञान": "mausam-vigyan",
 "विज्ञान": "vigyan",
 "प्रौद्योगिकी": "technology",
 "तकनीक": "takneek",
 "कोड": "code",
 "कोड।": "code.",
 "डिजिटल": "digital",
 "स्क्रीन": "screen",
 "फ़ोन": "phone",
 "मोबाइल": "mobile",
 "मोबाइल।": "mobile.",
 "नंबर": "number",
 "नंबरों": "numbers",
 "नंबर।": "number.",
 "नंबरों।": "numbers.",
 "गाड़ी": "gaadi",
 "गाड़ियों": "gaadiyon",
 "वाहन": "vahaan",
 "वाहनों": "vahaanon",
 "वाहन।": "vahaan.",
 "चाबी": "chaabi",
 "चाबी।": "chaabi.",
 "घर-गाड़ी": "ghar-gaadi",
 "काग़ज़ात": "kaagzaat",
 "काग़ज़": "kaagaz",
 "काग़ज़।": "kaagaz.",
 "दस्तख़त": "dastakhat",
 "साइन": "sign",
 "साइन।": "sign.",
 "साइन करें": "sign karo",
 "पुरस्कृत": "puraskrit",
 "पुरस्कार": "puraskaar",
 "इनाम": "inaam",
 "इनामों": "inaamon",
 "इनाम।": "inaam.",
 "पुरस्कार।": "puraskaar.",
 "धोखाधड़ी": "dhokhadhadi",
 "धोखाधड़ी।": "dhokhadhadi.",
 "ठगी": "thagi",
 "जरूर": "zaroor",
 "ज़रूर": "zaroor",
 "ज़रूरत": "zaroorat",
 "आवश्यकता": "aavashyakta",
 "ज़रूरतों": "zarooraton",
 "पक्का": "pakka",
 "पक्का।": "pakka.",
 "पक्की": "pakki",
 "अवश्य": "avashya",
 "निश्चित": "nishchit",
 "निश्चित।": "nishchit.",
 "गारंटी": "guarantee",
 "गारंटी।": "guarantee.",
 "संभव": "sambhav",
 "संभव।": "sambhav.",
 "संभावना": "sambhavna",
 "संभावनाएँ": "sambhavanaayein",
 "संभावना।": "sambhavna.",
 "मुमकिन": "mumkin",
 "मुमकिन।": "mumkin.",
 "शायद": "shaayad",
 "शायद।": "shaayad.",
 "शायद।।": "shaayad.",
 "कदाचित": "kadaachit",
 "प्रवृत्ति": "pravritti",
 "प्रवृत्तियाँ": "pravrittiyaan",
 "रुझान": "rujhaan",
 "रुझान।": "rujhaan.",
 "छिपा": "chhipa",
 "छिपा।": "chhipa.",
 "छिपे": "chhipe",
 "छिपे।": "chhipe.",
 "पितामह": "pitamah",
 "पितामह।": "pitamah.",
 "प्रपौत्र": "prapautra",
 "परपोते": "parpote",
 "परपोते।": "parpote.",
 "पुत्र": "putra",
 "पुत्री": "putri",
 "बेटा": "beta",
 "बेटी": "beti",
 "भाई": "bhai",
 "बहन": "behen",
 "मामा": "mama",
 "चाचा": "chacha",
 "नाना": "nana",
 "दादा": "dada",
 "दादी": "dadi",
 "नानी": "nani",
 "ससुर": "sasur",
 "सास": "saas",
 "जेठ": "jeth",
 "देवर": "devar",
 "नंद": "nand",
 "भाभी": "bhabhi",
 "देवरानी": "devraani",
 "जेठानी": "jethaani",
 "प्रेमी": "premi",
 "प्रेमिका": "premika",
 "पति": "pati",
 "पत्नी": "patni",
 "जीवनसाथी": "jeevansathi",
 "वर": "var",
 "वधू": "vadhoo",
 "लड़का": "ladka",
 "लड़की": "ladki",
 "लड़के": "ladke",
 "लड़कों": "ladkon",
 "लड़कियाँ": "ladkiyaan",
 "स्त्री": "stree",
 "स्त्री।": "stree.",
 "नारी": "naari",
 "महिला": "mahila",
 "आदमी": "aadmi",
 "आदमियों": "aadmiyon",
 "इंसान": "insaan",
 "इंसानों": "insaanon",
 "इंसान।": "insaan.",
 "व्यक्ति": "vyakti",
 "व्यक्ति।": "vyakti.",
 "मनुष्य": "manushya",
 "जीव": "jeev",
 "जीव।": "jeev.",
 "प्राणी": "praani",
 "मुझे": "mujhe",
 "तुम": "tum",
 "तुम्हें": "tumhein",
 "तुम्हारा": "tumhara",
 "हमारा": "hamara",
 "हमारे": "hamare",
 "हमें": "humein",
 "हमारा।": "hamara.",
 "हमने": "humne",
 "आपने।": "aapne.",
 "आप ही": "aap hi",
 "सेटिंग्स": "Settings",
 "सेटिंग्स।": "Settings.",
 "ब्राउज़र": "browser",
 "ब्राउज़र।": "browser.",
 "ब्रag": "browser",
 "व्यक्तिगत": "vyaktigat",
 "निजी": "niji",
 "प्राइवेट": "private",
 "निजी।": "niji.",
 "मुफ़्त": "free",
 "मुफ़्त।": "free.",
 "निःशुल्क": "Free",
 "वाचन": "vachan",
 "वाचन।": "vachan.",
 "सहमति": "sahamti",
 "सहमति-दीवार": "sahamti-deewar",
 "प्रमाण-पत्र": "pramaan-patra",
 "जन्म-प्रमाण-पत्र": "janm-pramaan-patra",
 "जन्म-नाम": "janm-naam",
 "जन्म-तिथि": "janm-tithi",
 "जन्म-तिथि।": "janm-tithi.",
 "जैसे:": "jaise:",
 "आरव": "Aarav",
 "मेहता": "Mehta",
 "डेमो": "demo",
 "डेमो।": "demo.",
 "प्रोफ़ाइल": "profile",
 "प्रोफ़ाइल।": "profile.",
 "प्रोफ़ाइलों": "profiles",
 "डेमो प्रोफ़ाइल": "demo profile",
 "भरी": "bhari",
 "भरा": "bhara",
 "भरी।": "bhari.",
 "खाली": "khaali",
 "डेटा": "data",
 "डेटा।": "data.",
 "स्टोरेज": "storage",
 "स्टोरेज।": "storage.",
 "एक्सपोर्ट": "export",
 "निर्यात": "export",
 "निर्यात/हटाएँ": "export/delete",
 "हटाएँ": "delete",
 "हटाएँ।": "delete.",
 "शेयर": "share",
 "पेज": "page",
 "पेजों": "pages",
 "रिपोर्ट": "report",
 "रिपोर्ट।": "report.",
 "रिपोर्टों": "reports",
 "अध्याय।": "adhyay.",
 "पुस्तक": "pustak",
 "किताब": "kitaab",
 "किताबों": "kitaabon",
 "किताबें": "kitaabein",
 "पत्रिका": "patrika",
 "जर्नल": "journal",
 "पत्रिका।": "patrika.",
 "जर्नल।": "journal.",
 "टिप्पणी": "tippani",
 "नोट": "note",
 "नोट्स": "notes",
 "सेव": "save",
 "सेव।": "save.",
 "मुख्य": "mukhya",
 "मुख्य।": "mukhya.",
 "महत्वपूर्ण": "mahatvapurn",
 "महत्वपूर्ण।": "mahatvapurn.",
 "केंद्रीय": "kendriya",
 "महत्व": "mahatv",
 "महत्व।": "mahatv.",
 "अहम": "aham",
 "अहम।": "aham.",
 "तरीका": "tareeqa",
 "तरीके": "tareeqe",
 "तरीकों": "tareeqon",
 "प्रणाली": "pranali",
 "प्रणाली।": "pranali.",
 "सिस्टम": "system",
 "सिस्टम।": "system.",
 "सिस्टमों": "systems",
 "संरचना": "sanrachna",
 "ढाँचा": "dhaancha",
 "ढाँचे": "dhaanche",
 "नक्शा": "naksha",
 "नक्शा।": "naksha.",
 "विस्तारित": "vistarit",
 "विस्तारित।": "vistarit.",
 "विस्तार": "vistar",
 "विस्तार।": "vistar.",
 "तालिका": "table",
 "तालिका।": "table.",
 "ग्रिड": "grid",
 "ग्रिड।": "grid.",
 "ग्रिड में": "grid mein",
 "भरता": "bharta",
 "भरती": "bharti",
 "भरते": "bharte",
 "भरा।": "bhara.",
 "सेल": "cell",
 "सेल।": "cell.",
 "कोठरी": "kothri",
 "कोठरियों": "kothriyon",
 "कोठरी।": "kothri.",
 "प्लेन": "plane",
 "प्लेनों": "planen",
 "तल": "tal",
 "तलों": "talon",
 "विकर्ण": "vikarn",
 "विकर्णों": "vikarnon",
 "डायगोनल": "diagonal",
 "तीर": "teer",
 "तीर।": "teer.",
 "बाण": "baan",
 "बाण।": "baan.",
 "धनुष": "dhanush",
 "धनुष।": "dhanush.",
 "सुनना": "sunna",
 "सुनें": "sunein",
 "सुनो": "suno",
 "सुना": "suna",
 "सुनने": "sunne",
 "सुना।": "suna.",
 "सुनने।": "sunne.",
 "पूछना": "poochhna",
 "पूछो": "poochho",
 "पूछें": "poochhein",
 "पूछो।": "poochho.",
 "बोलना": "bolna",
 "बोलो": "bolo",
 "बोलो।": "bolo.",
 "पहनना": "pehenna",
 "पहनो": "pehno",
 "पहनें": "pehno",
 "पहनें।": "pehno.",
 "धारण": "dhaaran",
 "धारण करें": "dhaaran karo",
 "धारण करें।": "dhaaran karo.",
 "बाँधकर": "baandhkar",
 "बाँधकर।": "baandhkar.",
 "बाँधो": "baandho",
 "सेवा-भाव": "seva-bhaav",
 "सेवा-भाव।": "seva-bhaav.",
 "संबंध": "sambandh",
 "संबंध।": "sambandh.",
 "संबंधों": "sambandhon",
 "संबंधित": "sambandhit",
 "संबद्धता": "sambandhta",
 "संबद्धताएँ": "sambandhtaayein",
 "संबद्धता।": "sambandhta.",
 "संबद्धताएँ।": "sambandhtaayein.",
 "पारंपरिक": "traditional",
 "पारंपरिक।": "traditional.",
 "सांस्कृतिक": "saanskratik",
 "सांस्कृतिक।": "saanskratik.",
 "स्वीकृत": "sweekrit",
 "स्वीकृत।": "sweekrit.",
 "स्वीकार": "sweekaar",
 "स्वीकार।": "sweekaar.",
 "मान्य": "maanya",
 "मान्य।": "maanya.",
 "मान्यता": "maanyata",
 "मान्यता।": "maanyata.",
 "स्वीकृति": "sweekriti",
 "अनुसरण": "anusaran",
 "अनुसरण-परिवार": "harmony-parivaar",
 "अनुसरण-परिवार।": "harmony-",
 "मेल-खाता": "mel-khata",
 "मेल-खाता।": "mel-khata.",
 "मेल": "mel",
 "मेल।": "mel.",
 "अनुरूप": "anuroop",
 "अनुरूप।": "anuroop.",
 "सामंजस्य": "saamanjasya",
 "सामंजस्य।": "saamanjasya.",
 "तालमेल": "taalmel",
 "तालमेल।": "taalmel.",
 "सहयोग": "sahyog",
 "सहयोग।": "sahyog.",
 "सहायता": "sahayata",
 "मदद": "madad",
 "मदद।": "madad.",
 "विपक्षी": "vipakshi",
 "शत्रु": "shatru",
 "शत्रु।": "shatru.",
 "मैदान": "maidan",
 "मैदान।": "maidan.",
 "मैदानों": "maidanon",
 "खुला": "khula",
 "खुला।": "khula.",
 "बंद": "band",
 "बंद।": "band.",
 "घेरा": "ghera",
 "घेरा।": "ghera.",
 "घेराबंदी": "gherabandi",
 "अलगाव": "algaav",
 "विराम": "viraam",
 "विराम।": "viraam.",
 "पड़ाव": "padaav",
 "पड़ाव।": "padaav.",
 "सफ़र": "safar",
 "सफ़र।": "safar.",
 "विश्राम": "vishraam",
 "विश्राम।": "vishraam.",
 "आराम।": "aaraam.",
 "मरम्मतों": "marammaton",
 "फुर्सत": "fursat",
 "फुर्सत।": "fursat.",
 "मौक़ा": "mauqa",
 "मौक़ा।": "mauqa.",
 "अवसर।": "mauqa.",
 "विशेष": "vishesh",
 "विशेष।": "vishesh.",
 "खास": "khaas",
 "खास।": "khaas.",
 "साधारण": "saadharan",
 "साधारण।": "saadharan.",
 "असाधारण": "asaadharan",
 "असाधारण।": "asaadharan.",
 "अजीब": "ajeeb",
 "अजीब।": "ajeeb.",
 "अजीबोग़रीब": "ajeebogareeb",
 "अपवाद": "apvaad",
 "अपवाद।": "apvaad.",
 "प्रतिकूल": "pratikool",
 "अनुकूल": "anukool",
 "अनुकूल।": "anukool.",
 "हानि।": "haani.",
 "लाभ।": "laabh.",
 "नुकसान": "nuksaan",
 "नुकसान।": "nuksaan.",
 "फ़ायदा": "faayda",
 "फायदा": "faayda",
 "फ़ायदा।": "faayda.",
 "बढ़त": "badhat",
 "बढ़त।": "badhat.",
 "वृद्धि": "vridhi",
 "वृद्धि।": "vridhi.",
 "गिरावट": "giraavat",
 "गिरावट।": "giraavat.",
 "गिरावटों": "giraavaton",
 "अचानक": "achanak",
 "अचानक।": "achanak.",
 "क्रम": "kram",
 "क्रमों": "kramon",
 "सिलसिला": "silsila",
 "सिलसिला।": "silsila.",
 "शृंखला": "shrinkhala",
 "शृंखला।": "shrinkhala.",
 "कतार": "qatar",
 "कतार।": "qatar.",
 "कतारों": "qataaron",
 "पंक्ति": "pankti",
 "पंक्ति।": "pankti.",
 "स्थिति": "sthiti",
 "स्थिति।": "sthiti.",
 "हालत": "haalat",
 "हालत।": "haalat.",
 "हालतें": "haalatein",
 "हाल": "haal",
 "हाल।": "haal.",
 "का-हाल": "ka-haal",
 "अभी का हाल": "Abhi ka haal",
 "अभी का हाल।": "Abhi ka haal.",
 "अभी-का-हाल": "Abhi ka haal",
 "कहानी": "kahaani",
 "कहानी।": "kahaani.",
 "कहानियाँ": "kahaaniyaan",
 "कहानियाँ।": "kahaaniyaan.",
 "गाथा": "gaatha",
 "गाथा।": "gaatha.",
 "स्टोरी": "story",
 "स्टोरी।": "story.",
 "कथा": "katha",
 "कथा।": "katha.",
 "इतिहास": "itihaas",
 "इतिहास।": "itihaas.",
 "भूतकाल": "bhootkaal",
 "भूतकाल।": "bhootkaal.",
 "भविष्यवाणी": "bhavishyavaani",
 "भविष्यवाणी।": "bhavishyavaani.",
 "भविष्य-वाणी": "bhavishy-vaani",
 "भविष्य-वाणी।": "bhavishy-vaani.",
 "वाचन।।": "vachan.",
 "अनुमान": "anumaan",
 "अनुमान।": "anumaan.",
 "अनुमानों": "anumaanon",
 "पूर्वानुमान": "poorvanumaan",
 "पूर्वानुमान।": "poorvanumaan.",
 "predict करते हैं": "predict karte hain",
 "predict करते हैं।": "predict karte hain.",
 "predict करता है।": "predict karta hai.",
 "predict कarate हैं।": "predict karte hain.",
 "प्रेम।": "prem.",
 "प्यार।": "pyaar.",
 "माँ।": "Maa.",
 "माँ के आशीर्वाद से": "Maa ke aashirwaad se",
 "भोलेनाथ की कृपा से": "Bholenath ki kripa se",
 "अंकों की माया": "Ankon Ki Maya",
 "कर्मिक": "karmic",
 "कर्मिक।": "karmic.",
 "कर्मिक-ऋण": "karmic-rin",
 "कर्मिक-ऋण।": "karmic-rin.",
 "कर्मिक-पाठ": "karmic-paath",
 "कर्मिक-पाठ।": "karmic-paath.",
 "कर्मिक ऋण": "karmic rin",
 "कर्मिक ऋण।": "karmic rin.",
 "कर्मिक पाठ": "karmic paath",
 "कर्मिक पाठ।": "karmic paath.",
 "कर्म": "karm",
 "कर्म।": "karm.",
 "पूर्व-जन्म": "poorva-janm",
 "पिछले जन्म": "pichhle janm",
 "पिछले जन्म।": "pichhle janm.",
 "जन्मों": "janmon",
 "जन्मों।": "janmon.",
 "स्वप्नवाणी": "sapnevaani",
 "स्वप्न।": "sapne.",
 "रुझानों": "rujhaanon",
 "प्रवृत्ति।": "pravritti.",
 "सप्तधान्य": "saptdhaanya",
 "सप्तधान्य।": "saptdhaanya.",
 "कांस्य": "kaansya",
 "रक्त": "rakt",
 "रक्त वस्त्र": "rakt vastra",
 "रक्त वस्त्र।": "rakt vastra.",
 "लाल चंदन": "laal chandan",
 "लाल चंदन।": "laal chandan.",
 "चाँदनी": "chaandni",
 "चाँदनी।": "chaandni.",
 "लहसुनियाँ": "lehsuniya",
 "लहसुनियाँ।": "lehsuniya.",
 "कस्तूरी": "kastoori",
 "कम्बल": "kambal",
 "कम्बल।": "kambal.",
 "उड़द": "urad",
 "उड़द।": "urad.",
 "सफ़ेद चंदन": "safed chandan",
 "सफ़ेद चंदन।": "safed chandan.",
 "श्वेत वस्त्र": "shwet vastra",
 "श्वेत वस्त्र।": "shwet vastra.",
 "श्वेत पुष्प": "shwet pushp",
 "श्वेत पुष्प।": "shwet pushp.",
 "पीले पुष्प": "peele pushp",
 "पीले पुष्प।": "peele pushp.",
 "धर्मग्रंथ": "dharmgranth",
 "धर्मग्रंथ।": "dharmgranth.",
 "पीली मिठाई": "peeli mithai",
 "पीली मिठाई।": "peeli mithai.",
 "मैस": "tail",
 "मैस।": "tail.",
 "सरसों": "sarson",
 "सरसों।": "sarson.",
 "काले जूते": "kaale joote",
 "काले जूते।": "kaale joote.",
 "काले पुष्प": "kaale pushp",
 "काले पुष्प।": "kaale pushp.",
 "काला वस्त्र": "kaala vastra",
 "काला वस्त्र।": "kaala vastra.",
 "मूँगा।": "Moonga.",
 "काले तिल": "kaale til",
 "काले तिल।": "kaale til.",
 "लाल कनेर": "laal kaner",
 "लाल कनेर।": "laal kaner.",
 "लाल वस्त्र": "laal vastra",
 "लाल वस्त्र।": "laal vastra.",
 "सप्ताह": "hafta",
 "सप्ताह।": "hafta.",
 "सप्ताहों": "hafton",
 "सप्ताहांत": "weekend",
 "सप्ताहांत।": "weekend.",
 "सप्ताह में": "hafte mein",
 "सप्ताह का": "hafte ka",
 "सप्ताह का।": "hafte ka.",
 "सप्ताह-समापन": "week-end",
 "सप्ताहांतों": "weekends",
 "अनुपस्थित": "absent",
 "उपस्थित": "maujood",
 "उपस्थित।": "maujood.",
 "अनुपस्थित।": "absent.",
 "पूर्णता": "poornata",
 "पूर्णता।": "poornata.",
 "कुल": "kul",
 "कुल।": "kul.",
 "योगफल": "yog-phal",
 "योगफल।": "yog-phal.",
 "मिलान": "milan",
 "मिलान।": "milan.",
 "गुण-मिलान": "guna-milan",
 "गुण-मिलान।": "guna-milan.",
 "गुण": "guna",
 "गुण।": "guna.",
 "गुणों": "gunon",
 "दोष": "dosh",
 "दोष।": "dosh.",
 "दोषों": "doshon",
 "मंगल-दोष": "mangal-dosh",
 "मंगल-दोष।": "mangal-dosh.",
 "काल-सर्प": "kala-sarp",
 "काल-सर्प।": "kala-sarp.",
 "परिक्षा": "pariksha",
 "परिक्षा।": "pariksha.",
 "कार्यक्षेत्र": "karyakshetra",
 "कार्यक्षेत्र।": "karyakshetra.",
 "क्षेत्र": "kshetra",
 "क्षेत्र।": "kshetra.",
 "क्षेत्रों": "kshetron",
 "क्षेत्रों।": "kshetron.",
 "मंगल दोष": "mangal dosh",
 "मंगल दोष।": "mangal dosh.",
 "काल सर्प": "kala sarp",
 "काल सर्प।": "kala sarp.",
 "बीज-संख्या": "beej-ank",
 "बीज-संख्या।": "beej-ank.",
 "बीज": "beej",
 "बीज।": "beej.",
 "संख्या": "sankhya",
 "संख्या।": "sankhya.",
 "संख्याओं": "sankhyaon",
 "संख्याओं।": "sankhyaon.",
 "प्रभाव": "prabhaav",
 "प्रभाव।": "prabhaav.",
 "प्रभावों": "prabhaavon",
 "प्रभावों।": "prabhaavon.",
 "प्रभावी": "prabhaavi",
 "प्रभावी।": "prabhaavi.",
 "व्यक्तित्व": "vyaktitva",
 "व्यक्तित्व।": "vyaktitva.",
 "आत्म-परिचय": "aatm-parichay",
 "आत्म-परिचय।": "aatm-parichay.",
 "परिचय": "parichay",
 "परिचय।": "parichay.",
 "आत्मनिरीक्षण": "aatm-nirikshan",
 "आत्मनिरीक्षण।": "aatm-nirikshan.",
 "निरीक्षण": "nirikshan",
 "निरीक्षण।": "nirikshan.",
 "आत्म-निरीक्षण": "aatm-nirikshan",
 "आत्म-निरीकसे": "aatm-niriksan",
 "आत्म-निरीक्षण।": "aatm-nirikshan.",
 "अंक-पुनरावृत्ति": "ank-punaraavritti",
 "अंक-पुनरावृत्ति (Repetitions)": "Ank-punaraavritti (Repetitions)",
 "पुनरावृत्ति": "repetition",
 "पुनरावृत्ति।।": "repetition.",
 "पुनरावृत्तियाँ": "repetitions",
 "पुनरावृत्तियाँ।": "repetitions.",
 "मुख्य अंक": "mukhya ank",
 "मुख्य अंक।": "mukhya ank.",
 "आपके मुख्य अंक": "aapke mukhya ank",
 "आपके मुख्य अंक।": "aapke mukhya ank.",
 "मुख्य अंकों": "mukhya ankon",
 "मुख्य अंकों।": "mukhya ankon.",
 "आपके मुख्य अंकों": "aapke mukhya ankon",
 "आपके मुख्य अंकों।": "aapke mukhya ankon.",
 "आपके मुज़": "aapke mukhya ankon.",
 "आपके मुख्य �अंकों।": "aapke mukhya ankon.",
 "मुख्य-अंक": "mukhya-ank",
 "मुख्य-अंक।": "mukhya-ank.",
 "समान": "samaan",
 "समान।": "samaan.",
 "एक जैसा": "ek jaisa",
 "एक जैसा।": "ek jaisa.",
 "एक जैसे": "ek jaise",
 "एक जैसे।": "ek jaise.",
 "दुबारा": "dobara",
 "दोबारा": "dobara",
 "दोबारा।": "dobara.",
 "बार": "baar",
 "बार।": "baar.",
 "बारी": "baari",
 "बारी।": "baari.",
 "बार-बार": "baar-baar",
 "बार-बार।": "baar-baar.",
 "ज़ोर": "zor",
 "ज़ोर।": "zor.",
 "ज़ोर-शोर": "zor-shor",
 "ज़ोर-शोर।": "zor-shor.",
 "मंत्र।": "mantra.",
 "जप-संख्या": "japa-count",
 "जप-संख्या।": "japa-count.",
 "मंत्र + जप": "Mantra + japa",
 "जप 7000": "japa 7000",
 "विस्तारित उपाय-तालिका": "Vistarit upay-table",
 "विस्तारित उपाय-तालिका।": "Vistarit upay-table.",
 "उपाय-तालिका": "upay-table",
 "उपाय-तालिका।": "upay-table.",
 "विस्तारित उपाय-तालिका — ग्रह, रत्न, मंत्र, दान": "Vistarit upay-table — graha, ratna, mantra, daan",
 "दैनिक अनुशासन — सप्ताह का अंक-पालन": "Roz ki discipline — hafte ka ank-practice",
 "विस्तारित उपाय--table": "Vistarit upay-table",
 "ग्रह, रत्न, मंत्र, दान": "graha, ratna, mantra, daan",
 "ग्रह, रत्न, मंत्र, दान।": "graha, ratna, mantra, daan.",
 "दैनिक अनुशासन": "roz ki discipline",
 "दैनिक अनुशासन।": "roz ki discipline.",
 "अंक-पालन": "ank-practice",
 "अंक-पालन।": "ank-practice.",
 "सप्ताह का अंक-पालन": "hafte ka ank-practice",
 "पोखराज": "Pukhraj",
 "चने की दाल": "chane ki daal",
 "कांस्य पात्र": "kaansya paatra",
 "कांस्य पात्र।": "kaansya paatra.",
 "सुगंधित द्रव्य": "sugandhit dravya",
 "सुगंधित द्रव्य।": "sugandhit dravya.",
 "दैनिक": "roz",
 "दैनिक।": "roz.",
 "साप्ताहिक": "weekly",
 "साप्ताहिक।": "weekly.",
 "साप्ताहिक।।": "weekly.",
 "मासिक": "monthly",
 "मासिक।": "monthly.",
 "वार्षिक": "yearly",
 "वार्षिक।": "yearly.",
 "दैनिक-पालन": "roz-practice",
 "पालन-पोषण": "paalan-poshan",
 "पालन-पोषण।": "paalan-poshan.",
 "आशीर्वाद।": "aashirwaad.",
 "कृपा।": "kripa.",
 "संरक्षक": "sanrakshak",
 "नेतृत्व, अधिकार, प्रतिष्ठा": "leadership, adhikaar, pratishtha",
 "भावना, अंतर्ज्ञान, जन-हृदय": "bhaavna, antargyaan, jan-dil",
 "ज्ञान, विस्तार, धन-वृद्धि": "gyaan, vistar, dhan-vridhi",
 "नवीनता, उलट-बाज़ी, अपरंपरागत": "navinta, ulat-baazi, apara-ramparaagat",
 "तर्क, व्यापार, संवाद": "tark, vyaapaar, samvaad",
 "विलास, सौंदर्य, प्रेम": "vilaas, saundarya, prem",
 "अध्यात्म, अनुसंधान, वैराग्य": "adhyatm, anushandhaan, vairagya",
 "अनुशासन, कर्म, सहनशक्ति": "anushasan, karm, sahanshakti",
 "साहस, कार्य, ऊर्जा": "saahas, kaarya, oorja",
 "मित्र ग्रह": "mitra graha",
 "मित्र ग्रह।": "mitra graha.",
 "तनाव ग्रह": "tanaav graha",
 "तनाव ग्रह।": "tanaav graha.",
 "कर्मिक जोड़ी (राहु-केतु)": "karmic jodi (Rahu-Ketu)",
 "कर्मिक जोड़ी (राहु-केतु)।": "karmic jodi (Rahu-Ketu).",
 "सम-भाव": "sam-bhaav",
 "सम-भाव।": "sam-bhaav.",
 "मूलांक — चालक अंक": "Mulank — chaalak ank",
 "भाग्यांक — नियति अंक": "Bhagyank — niyati ank",
 "नामांक — नाम-अंक": "Namank — naam-ank",
 "अंक दशा": "Ank Dasha",
 "अंक दशा।": "Ank Dasha.",
 "पूर्ण।": "poora.",
 "आधार / Basis": "Basis",
 "आधार।": "aadhaar.",
 "इसी आधार पर हम आपके लिए यह predict करते हैं।": "Isi basis par hum aapke liye yeh predict karte hain.",
 "चिंतन-विषय": "chintan-vishay",
 "चिंतन-विषय।": "chintan-vishay.",
 "परंपरा में कहा गया है — “सोना सभी ग्रह का दान है”: अगर कोई विशेष �दान-वस्तु उपलब्ध न हो, तो सोना (या सोने की छोटी वस्तु) सभी ग्रहों के दान में स्वीकार माना जाता है।": "Parampara mein kaha gaya hai — \"sona sabhi grahon ka daan hai\": agar koi vishesh daan-vastu uplabdh na ho, to sona (ya sone ki chhoti vastu) sabhi grahon ke daan mein sweekrit maana jaata hai.",
 "परंपरा में कहा गया है — “सोना सभी ग्रह का दान है”: अगर कोई विशेष दान-वस्तु उपलब्ध �न हो, तो सोरा (या सोरे की छोटी वस्तु) सभी ग्रहों के दान में स्वीकार माना जाता है।": "Parampara mein kaha gaya hai — \"sona sabhi grahon ka daan hai\": ...",
 "परंपरा में कहा गया है — “सोना सभी ग्रह का द reworded": "...",
 "परंपरा में कहा गया है — “सोना सभी ग्रह का दान है”: अगर कोई विशेष दान-वस्तु उल्लेख न हो": "Parampara mein kaha gaya hai — sona sabhi grahon ka daan hai",
 "परंपरा में कहा गया है — “सoना सभी ग्रह का दान है”":"...",
   "सूची":"soochi","सूची।":"soochi.","सूची-में":"soochi mein",
   "पटिया":"patiya","पटिया।":"patiya.",
   "बहादुरों":"bahaduron","बहादुर":"bahadur","सत्ता":"satta","सत्ता।":"satta.",
   "मेहमान":"mehamaan","मेहमानों":"mehamaanon","मेहमान-सूची":"mehamaan-soochi",
   "मेहमानों-सूची":"mehamaanon-soochi","मेहमान-सूची।":"mehamaan-soochi.",
   "दरवाज़े":"darwaaze","दरवाज़े।":"darwaaze.","दरवाज़":"darwaaz",
   "रेखा-रेखा":"rekha-rekha",
   "संतान":"santaan","संतान।":"santaan.","संतान।।":"santaan.",
   "उमंग":"umang","सामंजस्य":"saamanjasya","मिलाकर":"milakar",
   "घटनाओं":"ghatnaon","घटना":"ghatna","घटना।":"ghatna.",
   "घटनाओं।":"ghatnaon.","घटनाओं-से":"ghatnaon se",
   "बनती":"banti","बनती।":"banti.","बनते":"bante","बनता":"banta",
   "अनुसार":"anusaar","अनुसार।":"anusaar.","अनुसार-":"anusaar-",
   "जल्दी":"jaldi","जल्दी।":"jaldi.","रहता":"rehata","रहती":"rehti",
   "रहते":"rehte","रहता।":"rehata.",
   "बनती है":"banti hai","बनते हैं":"bante hain",
 "दीजिए": "do",
"दीजिए।": "do.",
"दीजिये": "do",
"दावा": "daava",
"नया": "naya",
"नया।": "naya.",
"कीजिए": "karo",
"कीजिए।": "karo.",
"रिश्तों": "rishton",
"सींचिए": "seencho",
"कीजिये": "karo",
"साझेदारियाँ": "saajhedariyaan",
"साझेदारी": "saajhedari",
"साझेदार": "saajhedaar",
"मिलेगी": "milegi",
"मिलेगा": "milega",
"मिलेंगे": "milenge",
"मिलेंगी": "milengi",
"पकेंगी": "pakengi",
"पकेंगे": "pakenge",
"खुलेगा": "khulega",
"खुलेंगी": "khulengi",
"खुलेगी": "khulegi",
"खुलेंगे": "khulenge",
"आएगा": "aayega",
"आएगी": "aayegi",
"आएंगे": "aayenge",
"आएंगी": "aayengi",
"मिलेगी।": "milegi.",
"मिलेगा।": "milega.",
"हफ़्ते": "hafte",
"हफ़्ते।": "hafte.",
"हफ़्ता": "hafta",
"हफ़्ते-भर": "hafte-bhar",
"प्रकाशित": "prakashit",
"प्रकाशित करें": "publish karo",
"प्रस्तुत करें": "present karo",
"बोलें": "bolo",
"रखिए।": "rakho.",
"रखिए": "rakho",
"दिखना": "dikhna",
"सिखाना": "sikhaana",
"सृजन": "srijan",
"पीछे": "peechhe",
"उठाकर": "uthaakar",
"सामने": "saamne",
"लोगों": "logon",
"ध्यान": "dhyaan",
"वर्ष": "saal",
"वर्ष।": "saal.",
"वर्ष है": "saal hai",
"वाला": "waala",
"वाली": "waali",
"वाले": "waale",
"चक्रवृद्धि": "chakravriddhi",
"ढोएगा": "dhoega",
"झटपट": "jhatpat",
"धैर्य-वर्ष": "dhairya-saal",
"नाम-दूर-जाने": "naam-door-jaane",
"रखिए": "rakho",
"रखिए।": "rakho.",
"रखिएगा": "rakhoge",
"रखिएगी": "rakhogi",
"करें": "karein",
"करें।": "karein.",
"बनाएं": "banao",
"बनाएँ": "banao",
"लेखा": "lekha",
"लेखा।": "lekha.",
"बही": "bahee",
"बही।": "bahee.",
"अंक-पुनरावृत्ति": "ank-repetition",
"पुनरावृत्ति": "repetition",
"पुनरावृत्तियाँ": "repetitions",
"अंक-पुनरावृत्ति (Repetitions)": "Ank-Repetitions",
"भाग्यांक भी ग्रिड में भरता है": "Bhagyank bhi grid mein bharta hai",
"बड़े साल — समय-रेखा बड़ी घटनाओं से बनती है": "Bade saal — samay-rekha badi ghatnaon se banti hai",
"शादी-प्यार": "shaadi-pyaar",
"नौकरी/एडमिशन": "naukri/admission",
"विरासत": "virasat",
"डबल 1": "Double 1",
"गुरु का झंडा — टीचर/स्पीकर": "Guru ka jhanda — teacher/speaker",
"गुरु का झंडा": "Guru ka jhanda",
"बेचैनी": "bechaini",
"गहरा-पर-विलंबित": "gehra-par-vilambit",
"आधार / Basis": "Basis",
"इसी आधार पर हम आपके लिए यह predict करते हैं।": "Isi basis par hum aapke liye yeh predict karte hain.",
"अंक-चक्र": "Ank-chakra",
"अभी का हाल": "Abhi ka haal",
"प्रातः सूर्य-जल अर्पण,": "Praatah soory-jal arpan,",
"रविवार 'ॐ सुर्याय नमः' का 108 जप।": "Ravivaar 'ॐ Suryaya Namah' ka 108 japa.",
"सोमवार श्वेत दान,": "Somvaar shwet daan,",
"'ॐ चंद्राय नमः' का 108 जप।": "'ॐ Chandraya Namah' ka 108 japa.",
"गुरुवार हल्दी दान,": "Guruvaar haldi daan,",
"'ॐ गुरवे नमः' 108 जप; दो मेज़ें चुनें, बाक़ी मना करें।": "'ॐ Gurave Namah' 108 japa; do options chuno, baaki reject karo.",
"शनि के लिए शनिवार तेल-दान; अंक 4 के लिए रोज़ बही-खाता,": "Shani ke liye Shanivaar tail-daan; ank 4 ke liye roz hisaab-kitaab,",
"शनिवार 'ॐ राहवे नमः' 108 जप, और बड़ा लॉन्च": "Shanivaar 'ॐ Rahave Namah' 108 japa, aur bada launch",
"बुधवार हरे वस्त्र,": "Budhvaar hare vastra,",
"'ॐ बुधाय नमः' 108 जप; हर सौदा साइन से पहले लिखें।": "'ॐ Budhaya Namah' 108 japa; har sauda sign se pehle likho.",
"शुक्रवार श्वेत दान,": "Shukravaar shwet daan,",
"'ॐ शुक्राय नमः' 108 जप; पारिवारिक वादा पहले, व्यापारिक बाद।": "'ॐ Shukraya Namah' 108 japa; parivaarik waada pehle, business baad.",
"शनिवार 'ॐ केतवे नमः' 108 जप, क्रीम/भूरा दान;": "Shanivaar 'ॐ Ketave Namah' 108 japa, cream/bhoora daan;",
"एक कला चुपचाप में महारत — मंच अंक-दशा 8/1 पर फिर खुलेगा": "ek kala mein chupke se maharat — manch ank-dasha 8/1 par phir khulega",
"शनिवार तेल-दान,": "Shanivaar tail-daan,",
"'ॐ शनैश्चराय नमः' 108 जप; हर सौदा साफ़, हर वादा निभा।": "'ॐ Shanicharaya Namah' 108 japa; har sauda saaf, har waada nibhao.",
"मंगलवार मसूर दान,": "Mangalvaar masoor daan,",
"'ॐ मंगलाय नमः' 108 जप; टकराव की जगह समापन चुनें।": "'ॐ Mangalaya Namah' 108 japa; takraav ki jagah samaapan chuno.",
"लिखो": "likho",
"लिखो।": "likho.",
"बढ़ाओ": "badhao",
"व्यापार और संपर्क बढ़ाओ": "vyaapaar aur sampark badhao",
"कहो": "kaho",
"हा कहो": "ha kaho",
"माँगो": "maango",
"pad माँगो": "pad maango",
"चुका दो": "chuka do",
"चुका दो toh": "chuka do toh",
"मेहनत": "mehnat",
"मेहनत।": "mehnat.",
"मेहनती": "mehnati",
"शॉर्टकट": "shortcut",
"शॉर्टकट।": "shortcut.",
"शॉर्टकटों": "shortcuts",
"बनाइए": "banao",
"बनाइए।": "banao.",
"बनाओ": "banao",
"टालिए": "taalo",
"टालिए।": "taalo.",
"टालें": "taalo",
"टालें।": "taalo.",
"अभ्यास": "abhyas",
"उठाओ": "uthao",
"उठाइए": "uthao",
"चुनें": "chuno",
"चुनें।": "chuno.",
"चुनो": "chuno",
"बांधें": "baandho",
"बांधें।": "baandho.",
"बाँधें": "baandho",
"खेलें": "khelo",
"खेलें।": "khelo.",
"साफ़": "saaf",
"साफ़।": "saaf.",
"ubaaoo": "ubau",
"ubau": "uhaaro",
"banaaie": "banao",
"मेहनत": "mehnat",
"अब बना system": "ab bana hua system",
"चक्र का सबसे": "cycle ka sabse",
"वर्ष": "saal",
"ab bana": "ab bana hua",
"कमाई": "kamai",
"कमाई।": "kamai.",
"ग्राफ़": "graph",
"बदलाव": "badlaav",
"बदलाव।": "badlaav.",
"बदलावों": "badlaavon",
"'ॐ सुर्याय नमः'": "'ॐ Suryaya Namah'",
"'ॐ चंद्राय नमः'": "'ॐ Chandraya Namah'",
"'ॐ गुरवे नमः'": "'ॐ Gurave Namah'",
"'ॐ राहवे नमः'": "'ॐ Rahave Namah'",
"'ॐ बुधाय नमः'": "'ॐ Budhaya Namah'",
"'ॐ शुक्राय नमः'": "'ॐ Shukraya Namah'",
"'ॐ केतवे नमः'": "'ॐ Ketave Namah'",
"'ॐ शनैश्चराय नमः'": "'ॐ Shanicharaya Namah'",
"'ॐ मंगलाय नमः'": "'ॐ Mangalaya Namah'",
"का 108 जप।": "ka 108 japa.",
"108 जप;": "108 japa;",
"baqaya chuka दो toh": "baqaya chuka do toh",
"padaei": "pade",
}
